DATABASE_MANAGER_URL: ENC[AES256_GCM,data:emBn0/paRdbZwpTstCbdmBc+y2tnqHeBzl8AcuiltgLPiWvMgyJ0yIOzBj3hrLOmT+M=,iv:B6S7BArSOfGtAEpApSsdu7lgDNeoqDedFHMJvame5Qg=,tag:NoXAkRoaV561MkN8bkqpCw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-05-11T11:16:58Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gHzzs0N7+kYwEkyL3bvEnHsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjgFWlhThhSVl8GEeAgEQgDuFyEP6XJD0HgVX6LTrqn0B5AprkRLBibYlJCAiaFPFKzZ9/pRWN5QaxWLiCD58NuzepBho0Alaw9U4eQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-30T08:00:37Z"
    mac: ENC[AES256_GCM,data:DgTPMwOL4vAXoOvmHyJ92lhmkG5qF083Jcb9zy1jNuhITpY2KLhlbCaqt+C67Fw4bz2jLJRAe65TPkFHT8XJsEUoGHbFa2nQXHEu0Unpvnc+UvGf7ESTh9pxUXTf9SYt2/5i4L+o8MUTYT8BjeWBy+NYIYik33I1CC/67sIEaP8=,iv:XOS9SUErR9A/WMFRRXva5PDVB2q3oSaU705AQS8eA9o=,tag:6ZGgHRmeXO6PDYv7g0aXpw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
