version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    # Ignoring these dependencies until there's a version that doesn't cause build issues for us, currently @v0.27.4
    ignore:
      - dependency-name: "github.com/orlangure/gnomock"
      - dependency-name: "k8s.io/api"
      - dependency-name: "k8s.io/apimachinery"
      - dependency-name: "k8s.io/client-go"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
