version: "2"
linters:
  enable:
    - bodyclose
    - forbidigo
    - gocritic
    - gosec
    - sloglint
  settings:
    forbidigo:
      forbid:
        - pattern: ^log\.Print.*$
          msg: Use log/slog to log
        - pattern: ^log\.Fatal.*$
          msg: Only main should call os.Exit(). Return an error instead
        - pattern: ^gin.Context.(Deadline|Done|Err|Value|Set|Get|MustGet|GetString|GetBool|GetInt|GetInt64|GetUint|GetUint64|GetFloat64|GetTime|GetDuration|GetStringSlice|GetStringMap|GetStringMapString|GetStringMapStringSlice)$
          msg: Always use https://pkg.go.dev/net/http#Request.Context instead of gin.Context
      analyze-types: true
    sloglint:
      no-global: all
      context: scope
      static-msg: true
      key-naming-case: camel
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
