fail_fast: true

default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports
        args:
          - "-w"
      - id: go-mod-tidy

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.2
    hooks:
      - id: golangci-lint
        args: [--verbose]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/dhis2-sre/im-tooling
    rev: v0.0.2
    hooks:
      - id: swagger-validation
