x-service: &common-dev-test
  build:
    context: .
    target: build
  env_file:
    - .env
  volumes:
    - .:/src
  working_dir: /src

services:
  prod:
    image: dhis2/im-manager:${IMAGE_TAG:-latest}
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - prod

  test:
    <<: *common-dev-test
    command: /bin/sh -c 'go test ./...'
    profiles:
      - test

  test-coverage:
    <<: *common-dev-test
    command: /bin/sh -c 'go test -coverprofile=./coverage.out ./... && go tool cover -html=./coverage.out -o ./coverage.html'
    profiles:
      - test-coverage

  dev:
    <<: *common-dev-test
    ports:
      - "8080:8080"
    command: reflex -r "Dockerfile|\.go|\.yml$$" -s -- sh -c "go run ./cmd/serve"
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    profiles:
      - dev

  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USERNAME}", "-d", "${DATABASE_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
    profiles:
      - dev
      - prod

  rabbitmq:
    image: bitnami/rabbitmq:3.13
    ports:
      - "127.0.0.1:5552:5552" # Stream
      - "127.0.0.1:5672:5672" # regular AMQP
      - "127.0.0.1:15672:15672" # management UI
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
      RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: "100MB"
      RABBITMQ_PLUGINS: "rabbitmq_management,rabbitmq_management_agent,rabbitmq_stream,rabbitmq_stream_management"
    healthcheck:
      # https://www.rabbitmq.com/docs/monitoring#stage-3
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 5s
      timeout: 3s
      retries: 5
    profiles:
      - dev
      - prod

  redis:
    image: redis:6.2.5-alpine3.14
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis:/data
    profiles:
      - dev
      - prod

  minio:
    image: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - minio:/data
    profiles:
      - dev

  minio-bucket:
    image: minio/mc:RELEASE.2023-07-21T20-44-27Z
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
        mc alias set dev http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        mc admin user add dev ${MINIO_USER} ${MINIO_PASSWORD}
        mc admin policy attach dev readwrite --user ${MINIO_USER}
        mc mb dev/${S3_BUCKET}"
    profiles:
      - dev

volumes:
  database:
  redis:
  minio:
