x-k3s-common: &k3s-common
  image: rancher/k3s:v1.31.1-k3s1
  privileged: true
  command: server
  environment:
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666

x-k3s-register: &k3s-register
  image: curlimages/curl:7.82.0
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ./scripts:/scripts
    - k3s-config-dev:/output
  command: [ "/bin/sh", "/scripts/register-k3s-cluster.sh" ]

services:
  k3s-dev:
    <<: *k3s-common
    ports:
      #- "80:80"
      #- "443:443"
      - "6443:6443"
    volumes:
      - k3s-data-dev:/var/lib/rancher/k3s
      - k3s-config-dev:/output

  k3s-dev-register:
    <<: *k3s-register
    environment:
      IM_HOSTNAME: "host.docker.internal:8080"
      IM_ADMIN_EMAIL: "andreas@dhis2.org"
      IM_ADMIN_PASSWORD: "somepassword"
      GROUP_NAME: dev
      GROUP_HOSTNAME: dev
      GROUP_NAMESPACE: dev

  k3s-test:
    <<: *k3s-common
    ports:
      #- "80:80"
      #- "443:443"
      - "6444:6443"
    volumes:
      - k3s-data-test:/var/lib/rancher/k3s
      - k3s-config-test:/output

  k3s-test-register:
    <<: *k3s-register
    environment:
      IM_HOSTNAME: "host.docker.internal:8080"
      IM_ADMIN_EMAIL: "andreas@dhis2.org"
      IM_ADMIN_PASSWORD: "somepassword"
      GROUP_NAME: test
      GROUP_HOSTNAME: test
      GROUP_NAMESPACE: test

  k3s-prod:
    <<: *k3s-common
    ports:
      #- "80:80"
      #- "443:443"
      - "6445:6443"
    volumes:
      - k3s-data-prod:/var/lib/rancher/k3s
      - k3s-config-prod:/output

  k3s-prod-register:
    <<: *k3s-register
    environment:
      IM_HOSTNAME: "host.docker.internal:8080"
      IM_ADMIN_EMAIL: "andreas@dhis2.org"
      IM_ADMIN_PASSWORD: "somepassword"
      GROUP_NAME: prod
      GROUP_HOSTNAME: prod
      GROUP_NAMESPACE: prod

volumes:
  k3s-data-dev:
  k3s-config-dev:
  k3s-data-test:
  k3s-config-test:
  k3s-data-prod:
  k3s-config-prod:
