apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/im-manager
deploy:
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: im-manager-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        artifactOverrides:
          image: dhis2/im-manager
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/values.yaml
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml

      - name: im-manager-postgresql-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/postgresql.yaml
