.im-group-chart-config: &im-group-chart-config
  createNamespace: true
  remoteChart: im-group
  repo: https://dhis2-sre.github.io/im-group
  version: 0.3.0

.im-group-prod-service-account-config: &im-group-prod-service-account-config
  setValues:
    serviceAccount:
      name: im-manager-prod
      namespace: instance-manager-prod
## TODO: Once we get Skaffold profiles working this should be uncommented
#    setValueTemplates:
#      corsAllowOrigins:
#        - "https://{{ .UI_URL }}"

apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: im-manager
build:
  artifacts:
    - image: dhis2/im-manager
  tagPolicy:
    inputDigest: { }
deploy:
  statusCheckDeadlineSeconds: 240
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - name: im-jaeger-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        remoteChart: jaeger
        repo: https://jaegertracing.github.io/helm-charts
        version: 3.4.0
        upgradeOnChange: true
        valuesFiles:
          - helm/data/values/{{ .CLASSIFICATION }}/jaeger.yaml

      - name: im-rabbitmq-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        remoteChart: rabbitmq
        repo: https://charts.bitnami.com/bitnami
        version: 14.4.2
        upgradeOnChange: true
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/rabbitmq.yaml
          - helm/data/values/{{ .CLASSIFICATION }}/rabbitmq.yaml
        setValueTemplates:
          global:
            security:
              allowInsecureImages: true
          image:
            repository: bitnamilegacy/rabbitmq

      - name: im-redis-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        version: 23.2.12
        upgradeOnChange: true
        valuesFiles:
          - helm/data/values/{{ .CLASSIFICATION }}/redis.yaml
        setValueTemplates:
          global:
            security:
              allowInsecureImages: true
          image:
            repository: bitnamilegacy/redis

      - name: im-manager-postgresql-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 13.2.30
        upgradeOnChange: true
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/postgresql.yaml
          - helm/data/values/{{ .CLASSIFICATION }}/postgresql.yaml
        setValueTemplates:
          global:
            security:
              allowInsecureImages: true
          image:
            repository: bitnamilegacy/postgresql

      - name: im-manager-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .CLASSIFICATION }}
        createNamespace: true
        chartPath: helm/chart
        setValueTemplates:
          corsAllowOrigins:
            - "{{ .UI_URL }}"
            - http://localhost:3000
          image:
            repository: dhis2/im-manager
          serviceAccount:
            annotations:
              "eks\\.amazonaws\\.com\\/role-arn": arn:aws:iam::767224633206:role/instance-cluster-production-im-manager-{{ .CLASSIFICATION }}
          ingress:
            enabled: true
            hostname: "{{ .API_HOSTNAME }}"
            certIssuer: cert-issuer-prod
          redis:
            host: im-redis-{{ .ENVIRONMENT }}-master.instance-manager-{{ .CLASSIFICATION }}.svc
          environment:
            ENVIRONMENT: "{{ .ENVIRONMENT }}"
            CLASSIFICATION: "{{ .CLASSIFICATION }}"
            HOSTNAME: "{{ .API_HOSTNAME }}"
            UI_URL: "{{ .UI_URL }}"
            INSTANCE_SERVICE_HOST: im-manager-{{ .ENVIRONMENT }}.instance-manager-{{ .CLASSIFICATION }}.svc:8080
            JAEGER_HOST: im-jaeger-{{ .ENVIRONMENT }}-collector.instance-manager-{{ .CLASSIFICATION }}.svc
            JAEGER_PORT: "14268"
            DATABASE_HOST: im-manager-postgresql-{{ .ENVIRONMENT }}.instance-manager-{{ .CLASSIFICATION }}.svc
            DATABASE_PORT: "5432"
            RABBITMQ_HOST: im-rabbitmq-{{ .ENVIRONMENT }}.instance-manager-{{ .CLASSIFICATION }}.svc
            RABBITMQ_PORT: "5672"
            RABBITMQ_STREAM_PORT: "5552"
            S3_BUCKET: im-databases-{{ .CLASSIFICATION }}
            S3_REGION: eu-west-1
            DEFAULT_TTL: "172800" # 48 hours
            PASSWORD_TOKEN_TTL: "900" # 15 minutes
            LOG_PRETTY_PRINT: "{{ .LOG_PRETTY_PRINT }}"
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/values.yaml
          - helm/data/values/{{ .CLASSIFICATION }}/values.yaml

profiles:
  - name: dev
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-dev-dev
          namespace: dev
          <<: *im-group-chart-config
          setValueTemplates:
            serviceAccount:
              name: im-manager-{{ .ENVIRONMENT }}
              namespace: instance-manager-{{ .CLASSIFICATION }}
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-whoami-{{ .ENVIRONMENT }}
          namespace: whoami
          <<: *im-group-chart-config
          setValueTemplates:
## TODO: Once we get Skaffold profiles working this should be uncommented
#            corsAllowOrigins:
#              - "http://localhost:3000"
#              - "http://localhost:5173"
#              - "{{ .UI_URL }}"
            serviceAccount:
              name: im-manager-{{ .ENVIRONMENT }}
              namespace: instance-manager-{{ .CLASSIFICATION }}

  - name: prod
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-dev
          namespace: dev
          <<: [*im-group-chart-config, *im-group-prod-service-account-config]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-play
          namespace: play
          <<: [*im-group-chart-config, *im-group-prod-service-account-config]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-qa
          namespace: qa
          <<: [*im-group-chart-config, *im-group-prod-service-account-config]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-meta-packages
          namespace: meta-packages
          <<: [*im-group-chart-config, *im-group-prod-service-account-config]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-design
          namespace: design
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-research
          namespace: research
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-android
          namespace: android
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-implement
          namespace: implement
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-emis
          namespace: emis
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]

      - op: add
        path: /deploy/helm/releases/-
        value:
          name: im-group-prod
          namespace: prod
          <<: [ *im-group-chart-config, *im-group-prod-service-account-config ]
