apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: im-manager
build:
  artifacts:
    - image: dhis2/im-manager
  tagPolicy:
    inputDigest: { }
deploy:
  statusCheckDeadlineSeconds: 240
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - name: im-rabbitmq-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: rabbitmq
        repo: https://charts.bitnami.com/bitnami
        version: 10.3.9
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/rabbitmq.yaml

      - name: im-manager-redis-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: redis
        repo: https://charts.bitnami.com/bitnami
        version: 17.6.0
        setValues:
          architecture: standalone
          auth:
            enabled: false

      - name: im-manager-postgresql-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 11.6.2
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/postgresql.yaml
          - helm/data/values/{{ .CLASSIFICATION }}/postgresql.yaml

      - name: im-manager-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        setValueTemplates:
          image:
            repository: dhis2/im-manager
          serviceAccount:
            annotations:
              eks\\.amazonaws\\.com\\/role-arn: arn:aws:iam::767224633206:role/instance-cluster-test-im-manager-{{ .ENVIRONMENT }}
          ingress:
            enabled: true
            hostname: api.im.{{ .ENVIRONMENT }}.test.c.dhis2.org
            certIssuer: cert-issuer-prod
          redis:
            host: im-manager-redis-{{ .ENVIRONMENT }}-master.instance-manager-{{ .ENVIRONMENT }}.svc
          environment:
            ENVIRONMENT: "{{ .ENVIRONMENT }}"
            INSTANCE_SERVICE_HOST: im-manager-{{ .ENVIRONMENT }}.instance-manager-{{ .ENVIRONMENT }}.svc:8080
            INSTANCE_SERVICE_BASE_PATH: /
            DATABASE_MANAGER_SERVICE_HOST: im-manager-{{ .ENVIRONMENT }}.instance-manager-{{ .ENVIRONMENT }}.svc:8080
            DATABASE_MANAGER_SERVICE_BASE_PATH: /
            DATABASE_HOST: im-manager-postgresql-{{ .ENVIRONMENT }}.instance-manager-{{ .ENVIRONMENT }}.svc
            DATABASE_PORT: "5432"
            RABBITMQ_HOST: im-rabbitmq-{{ .ENVIRONMENT }}.instance-manager-{{ .ENVIRONMENT }}.svc
            RABBITMQ_PORT: "5672"
            S3_BUCKET: test-db-manager-bucket
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .CLASSIFICATION }}/values.yaml

profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: im-group-whoami-{{ .ENVIRONMENT }}
            namespace: whoami
            createNamespace: true
            remoteChart: im-group
            repo: https://dhis2-sre.github.io/im-group
            version: 0.2.0
            setValueTemplates:
              serviceAccount:
                name: im-manager-{{ .ENVIRONMENT }}
                namespace: instance-manager-{{ .ENVIRONMENT }}

  - name: prod
    deploy:
      helm:
        releases:
          - name: im-group-dev
            namespace: dev
            createNamespace: true
            remoteChart: im-group
            repo: https://dhis2-sre.github.io/im-group
            version: 0.2.0
            setValues:
              serviceAccount:
                name: im-manager-prod
                namespace: instance-manager-prod

          - name: im-group-play
            namespace: play
            createNamespace: true
            remoteChart: im-group
            repo: https://dhis2-sre.github.io/im-group
            version: 0.2.0
            setValues:
              serviceAccount:
                name: im-manager-prod
                namespace: instance-manager-prod

          - name: im-group-qa
            namespace: qa
            createNamespace: true
            remoteChart: im-group
            repo: https://dhis2-sre.github.io/im-group
            version: 0.2.0
            setValues:
              serviceAccount:
                name: im-manager-prod
                namespace: instance-manager-prod

          - name: im-group-meta-packages
            namespace: meta-packages
            createNamespace: true
            remoteChart: im-group
            repo: https://dhis2-sre.github.io/im-group
            version: 0.2.0
            setValues:
              serviceAccount:
                name: im-manager-prod
                namespace: instance-manager-prod
