# hostnamePattern: %s-postgresql.%s.svc
# stackParameters: DATABASE_MANAGER_URL
releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/postgresql
    version: "{{ env "CHART_VERSION" | default "11.0.4" }}"
    verify: false
    values:
      - primary:
          podLabels:
            im-data-id: "{{ requiredEnv "INSTANCE_ID" }}"

          extraEnvVars:
            - name: DATABASE_MANAGER_URL
              value: {{ requiredEnv "DATABASE_MANAGER_URL" }}
            - name: DATABASE_ID
              value: "{{ requiredEnv "DATABASE_ID" }}"
            - name: IM_ACCESS_TOKEN
              value: {{ requiredEnv "IM_ACCESS_TOKEN" }}
            - name: DATABASE_USERNAME
              value: {{ env "DATABASE_USERNAME" | default "dhis" }}
            - name: DATABASE_PASSWORD
              value: {{ env "DATABASE_PASSWORD" | default "dhis" }}
            - name: DATABASE_NAME
              value: {{ env "DATABASE_NAME" | default "dhis2" }}

          persistence:
            size: {{ env "DATABASE_SIZE" | default "5Gi" }}

          initdb:
            scripts:
              seed.sh: |
                {{- readFile "./seed.sh" | indent 16 }}

      - image:
          tag: {{ env "DATABASE_VERSION" | default 10 }}

      - auth:
          username: {{ env "DATABASE_USERNAME" | default "dhis" }}
          password: {{ env "DATABASE_PASSWORD" | default "dhis" }}
          database: {{ env "DATABASE_NAME" | default "dhis2" }}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
