# hostnamePattern: %s-database-postgresql.%s.svc
# stackParameters: DATABASE_MANAGER_URL
releases:
  - name: {{ requiredEnv "INSTANCE_NAME" }}-database
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/postgresql
    version: "{{ env "CHART_VERSION" | default "11.9.8" }}"
    verify: false
    values:
      - commonLabels:
          im: "true"
          im-default: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "db"
          im-creation-timestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "172800" }}"

      - primary:
          extraEnvVars:
            - name: DATABASE_MANAGER_URL
              value: {{ requiredEnv "DATABASE_MANAGER_URL" }}
            - name: DATABASE_ID
              value: "{{ requiredEnv "DATABASE_ID" }}"
            - name: IM_ACCESS_TOKEN
              value: {{ requiredEnv "IM_ACCESS_TOKEN" }}
            - name: DATABASE_USERNAME
              value: {{ env "DATABASE_USERNAME" | default "dhis" }}
            - name: DATABASE_PASSWORD
              value: {{ env "DATABASE_PASSWORD" | default "dhis" }}
            - name: DATABASE_NAME
              value: {{ env "DATABASE_NAME" | default "dhis2" }}

          persistence:
            size: {{ env "DATABASE_SIZE" | default "5Gi" }}

          initdb:
            scripts:
              seed.sh: |
                {{- readFile "./seed.sh" | indent 16 }}

      - image:
          tag: {{ env "DATABASE_VERSION" | default "13.7.0" }}

      - auth:
          username: {{ env "DATABASE_USERNAME" | default "dhis" }}
          password: {{ env "DATABASE_PASSWORD" | default "dhis" }}
          database: {{ env "DATABASE_NAME" | default "dhis2" }}

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
