// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/dhis2-sre/im-manager/pkg/config"
	"github.com/dhis2-sre/im-manager/pkg/stack"
	"github.com/dhis2-sre/im-manager/pkg/storage"
	"gorm.io/gorm"
	"log"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configConfig := config.ProvideConfig()
	db := provideDatabase(configConfig)
	repository := stack.ProvideRepository(db)
	service := stack.ProvideService(repository)
	handler := stack.ProvideHandler(service)
	environment := ProvideEnvironment(configConfig, handler)
	return environment
}

// wire.go:

type Environment struct {
	Config       config.Config
	StackHandler stack.Handler
}

func ProvideEnvironment(config2 config.Config,

	stackHandler stack.Handler,
) Environment {
	return Environment{config2, stackHandler}
}

func provideDatabase(c config.Config) *gorm.DB {
	database, err := storage.ProvideDatabase(c)
	if err != nil {
		log.Fatalln(err)
	}
	return database
}
