# hostnamePattern: %s-database-postgresql.%s.svc
# stackParameters: DATABASE_MANAGER_URL,GOOGLE_AUTH_PROJECT_ID,GOOGLE_AUTH_PRIVATE_KEY_ID,GOOGLE_AUTH_PRIVATE_KEY,GOOGLE_AUTH_CLIENT_EMAIL,GOOGLE_AUTH_CLIENT_ID
releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: dhis2/core
    version: "{{ env "CHART_VERSION" | default "0.14.0" }}"
    values:
      - image:
          repository: dhis2/{{ env "IMAGE_REPOSITORY" | default "core" }}
          tag: "{{ env "IMAGE_TAG" | default "2.39.0" }}"
          pullPolicy: {{ env "IMAGE_PULL_POLICY" | default "IfNotPresent" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 8m
      - dhis2Home: "{{ env "DHIS2_HOME" | default "/opt/dhis2" }}"
      - catalinaOpts: "-Dcontext.path=/{{ requiredEnv "INSTANCE_NAME" }}"
      - javaOpts: "{{ env "JAVA_OPTS" | default "" }}"
      - startupProbe:
          failureThreshold: {{ env "STARTUP_PROBE_FAILURE_THRESHOLD" | default 26 }}
          periodSeconds: {{ env "STARTUP_PROBE_PERIOD_SECONDS" | default 5 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - livenessProbe:
          timeoutSeconds: {{ env "LIVENESS_PROBE_TIMEOUT_SECONDS" | default 1 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - readinessProbe:
          timeoutSeconds: {{ env "READINESS_PROBE_TIMEOUT_SECONDS" | default 1 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - commonLabels:
          im: "true"
          im-default: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "dhis2"
          im-creation-timestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "172800" }}"
      - dhisConfig: |
          connection.dialect = org.hibernate.dialect.PostgreSQLDialect
          connection.driver_class = org.postgresql.Driver
          connection.url = jdbc:postgresql://{{ requiredEnv "INSTANCE_NAME" }}-database-postgresql.{{ requiredEnv "INSTANCE_NAMESPACE" }}.svc/{{ env "DATABASE_NAME" | default "dhis2" }}
          connection.username = {{ env "DATABASE_USERNAME" | default "dhis" }}
          connection.password = {{ env "DATABASE_PASSWORD" | default "dhis" }}
          # Database schema behavior, can be validate, update, create, create-drop
          connection.schema = update
          # Server base URL
          server.base.url = https://{{ requiredEnv "INSTANCE_HOSTNAME" }}/{{ requiredEnv "INSTANCE_NAME" }}
          flyway.migrate_out_of_order = {{ env "FLYWAY_MIGRATE_OUT_OF_ORDER" | default false }}
          flyway.repair_before_migration = {{ env "FLYWAY_REPAIR_BEFORE_MIGRATION" | default false }}
          {{- if eq (env "INSTALL_REDIS" | default "false") "true" }}
          redis.enabled = on
          redis.cache.invalidation.enabled = on
          redis.host = {{ requiredEnv "INSTANCE_NAME" }}-redis-master.{{ requiredEnv "INSTANCE_NAMESPACE" }}.svc
          redis.port = 6379
          {{ end }}
      - googleAuth:
          projectId: "{{ env "GOOGLE_AUTH_PROJECT_ID" | default "" }}"
          privateKeyId: "{{ env "GOOGLE_AUTH_PRIVATE_KEY_ID" | default "" }}"
          privateKey: {{ env "GOOGLE_AUTH_PRIVATE_KEY" | default "" }}
          clientEmail: "{{ env "GOOGLE_AUTH_CLIENT_EMAIL" | default "" }}"
          clientId: "{{ env "GOOGLE_AUTH_CLIENT_ID" | default "" }}"
      - resources:
          requests:
            cpu: {{ env "CORE_RESOURCES_REQUESTS_CPU" | default "250m" }}
            memory: {{ env "CORE_RESOURCES_REQUESTS_MEMORY" | default "256Mi" }}

  - name: {{ requiredEnv "INSTANCE_NAME" }}-database
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/postgresql
    version: 11.9.8
    verify: false
    values:
      - commonLabels:
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "db"

      - primary:
          extraEnvVars:
            - name: DATABASE_MANAGER_URL
              value: {{ requiredEnv "DATABASE_MANAGER_URL" }}
            - name: DATABASE_ID
              value: "{{ requiredEnv "DATABASE_ID" }}"
            - name: IM_ACCESS_TOKEN
              value: {{ requiredEnv "IM_ACCESS_TOKEN" }}
            - name: DATABASE_USERNAME
              value: {{ env "DATABASE_USERNAME" | default "dhis" }}
            - name: DATABASE_PASSWORD
              value: {{ env "DATABASE_PASSWORD" | default "dhis" }}
            - name: DATABASE_NAME
              value: {{ env "DATABASE_NAME" | default "dhis2" }}

          persistence:
            size: {{ env "DATABASE_SIZE" | default "5Gi" }}

          initdb:
            scripts:
              seed.sh: |
                {{- readFile "./seed.sh" | indent 16 }}

          resources:
            requests:
              cpu: {{ env "DB_RESOURCES_REQUESTS_CPU" | default "250m" }}
              memory: {{ env "DB_RESOURCES_REQUESTS_MEMORY" | default "256Mi" }}

      - image:
          repository: dhis2/postgresql-curl
          tag: {{ env "DATABASE_VERSION" | default "13" }}

      - auth:
          username: {{ env "DATABASE_USERNAME" | default "dhis" }}
          password: {{ env "DATABASE_PASSWORD" | default "dhis" }}
          database: {{ env "DATABASE_NAME" | default "dhis2" }}

  - name: {{ requiredEnv "INSTANCE_NAME" }}-redis
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/redis
    version: 17.3.11
    verify: false
    installed: {{ env "INSTALL_REDIS" | default "false" }}
    values:
      - architecture: standalone
      - auth:
          enabled: false

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: dhis2
    url: https://dhis2-sre.github.io/dhis2-core-helm
  - name: runix
    url: https://helm.runix.net
