releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: tons/dhis2-core
    version: "{{ env "CHART_VERSION" | default "0.4.0" }}"
    values:
      - image:
          repository: dhis2/core
          tag: "{{ env "IMAGE_TAG" | default "2.36.0-tomcat-8.5.34-jre8-alpine" }}"
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
      - catalinaOpts: "-Dcontext.path=/{{ requiredEnv "INSTANCE_NAME" }}"
      - livenessProbe:
          initialDelaySeconds: 180
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - readinessProbe:
          initialDelaySeconds: 180
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - podLabels:
          dhis2: "true"
          dhis2-id: "{{ requiredEnv "INSTANCE_ID" }}"
          dhis2-ttl: "{{ env "INSTANCE_TTL" | default "" }}"
      - dhisConfig: |
          connection.dialect = org.hibernate.dialect.PostgreSQLDialect
          connection.driver_class = org.postgresql.Driver
          connection.url = jdbc:postgresql://{{ requiredEnv "INSTANCE_NAME" }}-database-postgresql.{{ requiredEnv "INSTANCE_NAMESPACE" }}.svc.cluster.local/dhis2
          connection.username = dhis
          connection.password = dhis
          # Database schema behavior, can be validate, update, create, create-drop
          connection.schema = update
          # Server base URL
          server.base.url = https://{{ requiredEnv "INSTANCE_HOSTNAME" }}/{{ requiredEnv "INSTANCE_NAME" }}
          flyway.migrate_out_of_order = {{ env "FLYWAY_MIGRATE_OUT_OF_ORDER" | default false }}
          flyway.repair_before_migration = {{ env "FLYWAY_REPAIR_BEFORE_MIGRATION" | default false }}

  - name: {{ requiredEnv "INSTANCE_NAME" }}-database
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/postgresql
    version: 11.0.4
    verify: false
    values:
      - primary:
          podLabels:
            dhis2-data-id: "{{ requiredEnv "INSTANCE_ID" }}"

          extraEnvVars:
            - name: DATABASE_ID
              value: "{{ requiredEnv "DATABASE_ID" }}"
            - name: IM_ACCESS_TOKEN
              value: {{ requiredEnv "IM_TOKEN" }}

          persistence:
            size: 5Gi

          initdb:
            scripts:
              seed.sh: |
                {{- readFile "./seed.sh" | indent 16 }}

      - image:
          tag: {{ env "DATABASE_VERSION" | default 10 }}

      - auth:
          username: dhis
          password: dhis
          database: dhis2

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: tons
    url: https://helm-charts.fitfit.dk
