DATABASE_MANAGER_URL: ENC[AES256_GCM,data:kv+IRl7O8mkD2e12oVmU7kRlGSA+abHG40Dq2f0lEU+lDPVBAoDkPvhuKHb5GTRW,iv:R+YV5zxxBEsv2yanXsS8uq0Pq/78kTB8D7UxOg0kWyk=,tag:klbqooa9isAwMqB75usJwg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-05-11T11:16:58Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gEtKolbIGsLIPj4iCxWK+t0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6sqguWZGwE7wlvpLAgEQgDv8nPE8WA7sEBdShHlEcJXeksx+V31rnmqi2FwxLjQt/KEKZ7MelKDZp8zfEXGogrgUtlKB1Y2ebP0usQ==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-06-06T13:55:44Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gGYR9Va8gtQg7GAJUUyIQ62AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb41wdhaKFDSWLxpeAgEQgDvI1jR1lp2AOqEdBc0f8DursXAP5jKnFD/wvYqYmcTRAHNTeH0PB+aU6c+U3Shk0gekPSFhBM7BJOZVMg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-10T08:28:45Z"
    mac: ENC[AES256_GCM,data:0hqZ9Axwml+klNcN+O9cdKMK63dM6BH4Y4GXeCgfYE9ZjO7XPxLdwXbMSJ8nIqjsyXPd7rLYAoqMf2vPNhqN+ct6m8cpb9iXeAdc7nthNLB8c7BiQiKoOLdBdgwdgWZTu7vmY78176N/fTkG+ogZDFQdweewxp6wzeqbjD+Sqbc=,iv:Mfch+W9bMDi2/7ufJzZDKOmOi60+FrsbYdPa6wkrzMg=,tag:kNAaOF/iohGSIMRDucdu7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
