DATABASE_MANAGER_URL: ENC[AES256_GCM,data:97p3UxI1y2Zl1Cra+UI5bN7sjr5NeiEloiBxLxOY8B1HTXuKL1TCg5AcelSzefBm,iv:MgSAyEeNdS7hgvhaeobEk9ppwJNE+3VMU3oyOW9jsXc=,tag:0WyDSNStePJDMIAFUGcWwg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-05-11T11:16:58Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gE5fPcB4Bhz2wxQUP9Tk0NlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoGB5nZ9wWh/D6eAiAgEQgDsSywa2SwYpDqQ+tpGxOdRSUhAiKu+RbJazO2esCr+WsFX2q/AUk76VySlf8gANatvUn+DxU+P/hjQj7Q==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-06-06T13:52:35Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gEgpEnxT3oy8osaTwSDTWWJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMM+Gt+9Re6djx2tZyAgEQgDvYEzlGJXm5JnmpAi/7wjwWFAMisKlkwFnYnbKt2s2FVCC4j4eYQYzL72YjSb2LcnaQMJdeVh6EbjD5Dg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-06T13:52:37Z"
    mac: ENC[AES256_GCM,data:tT4SW4vx8a4q0IoNM+bnl7I0YXoxNyLgmC2hsUe0HRsPVzYupImk7u0apDZ8rC5q8Cm6VzOSOEv3z1j4248khWbJlRnK/modvhKEBXqMC0R3FtdWKTTs0fhaI39Nq0ATCfBd8CKN7tHY8f6Q+b1sU3nPl2Fhn3QTnOijwdUCK3U=,iv:dJfAUjwkySwEKEQBJR1vE/RxcYwns5VVqWhNB8AYojE=,tag:fBcR3LXwoDc+JM30p8VamA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
