releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: tons/whoami-go
    version: "{{ env "CHART_VERSION" | default "0.9.0" }}"
    values:
      - replicaCount: {{ env "REPLICA_COUNT" | default "1" }}
      - image:
          #repository: tons/{{ env "IMAGE_REPOSITORY" | default "core" }}
          tag: "{{ env "IMAGE_TAG" | default "0.6.0" }}"
          pullPolicy: {{ env "IMAGE_PULL_POLICY" | default "IfNotPresent" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
      - commonLabels:
          im: "true"
          im-default: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "whoami"
          im-creationTimestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "" }}"

repositories:
  - name: tons
    url: https://helm-charts.fitfit.dk
