releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: tons/whoami-go
    version: "{{ requiredEnv "CHART_VERSION" }}"
    values:
      - replicaCount: {{ env "REPLICA_COUNT" | default "1" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
      - podLabels:
          im: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "" }}"

repositories:
  - name: tons
    url: https://helm-charts.fitfit.dk
