releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: dhis2-whoami-go/whoami-go
    version: "{{ env "CHART_VERSION" | default "0.9.0" }}"
    values:
      - replicaCount: {{ env "REPLICA_COUNT" | default "1" }}
      - image:
          repository: dhis2/{{ env "IMAGE_REPOSITORY" | default "whoami-go" }}
          tag: "{{ env "IMAGE_TAG" | default "0.6.0" }}"
          pullPolicy: {{ env "IMAGE_PULL_POLICY" | default "IfNotPresent" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
      - commonLabels:
          im: "true"
          im-default: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "whoami"
          im-creation-timestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ requiredEnv "INSTANCE_TTL" }}"

repositories:
  - name: dhis2-whoami-go
    url: https://dhis2-sre.github.io/whoami-go
