// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// NewCopyDatabaseParams creates a new CopyDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCopyDatabaseParams() *CopyDatabaseParams {
	return &CopyDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCopyDatabaseParamsWithTimeout creates a new CopyDatabaseParams object
// with the ability to set a timeout on a request.
func NewCopyDatabaseParamsWithTimeout(timeout time.Duration) *CopyDatabaseParams {
	return &CopyDatabaseParams{
		timeout: timeout,
	}
}

// NewCopyDatabaseParamsWithContext creates a new CopyDatabaseParams object
// with the ability to set a context for a request.
func NewCopyDatabaseParamsWithContext(ctx context.Context) *CopyDatabaseParams {
	return &CopyDatabaseParams{
		Context: ctx,
	}
}

// NewCopyDatabaseParamsWithHTTPClient creates a new CopyDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewCopyDatabaseParamsWithHTTPClient(client *http.Client) *CopyDatabaseParams {
	return &CopyDatabaseParams{
		HTTPClient: client,
	}
}

/*
CopyDatabaseParams contains all the parameters to send to the API endpoint

	for the copy database operation.

	Typically these are written to a http.Request.
*/
type CopyDatabaseParams struct {

	/* Body.

	   Copy database request body parameter
	*/
	Body *models.CopyDatabaseRequest

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the copy database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyDatabaseParams) WithDefaults() *CopyDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the copy database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CopyDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the copy database params
func (o *CopyDatabaseParams) WithTimeout(timeout time.Duration) *CopyDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy database params
func (o *CopyDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy database params
func (o *CopyDatabaseParams) WithContext(ctx context.Context) *CopyDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy database params
func (o *CopyDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy database params
func (o *CopyDatabaseParams) WithHTTPClient(client *http.Client) *CopyDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy database params
func (o *CopyDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the copy database params
func (o *CopyDatabaseParams) WithBody(body *models.CopyDatabaseRequest) *CopyDatabaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the copy database params
func (o *CopyDatabaseParams) SetBody(body *models.CopyDatabaseRequest) {
	o.Body = body
}

// WithID adds the id to the copy database params
func (o *CopyDatabaseParams) WithID(id uint64) *CopyDatabaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the copy database params
func (o *CopyDatabaseParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CopyDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
