// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// CreateExternalDownloadDatabaseReader is a Reader for the CreateExternalDownloadDatabase structure.
type CreateExternalDownloadDatabaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateExternalDownloadDatabaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateExternalDownloadDatabaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewCreateExternalDownloadDatabaseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateExternalDownloadDatabaseForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateExternalDownloadDatabaseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewCreateExternalDownloadDatabaseUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateExternalDownloadDatabaseOK creates a CreateExternalDownloadDatabaseOK with default headers values
func NewCreateExternalDownloadDatabaseOK() *CreateExternalDownloadDatabaseOK {
	return &CreateExternalDownloadDatabaseOK{}
}

/*
CreateExternalDownloadDatabaseOK describes a response with status code 200, with default header values.

CreateExternalDownloadDatabaseOK create external download database o k
*/
type CreateExternalDownloadDatabaseOK struct {
	Payload *models.ExternalDownload
}

// IsSuccess returns true when this create external download database o k response has a 2xx status code
func (o *CreateExternalDownloadDatabaseOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create external download database o k response has a 3xx status code
func (o *CreateExternalDownloadDatabaseOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create external download database o k response has a 4xx status code
func (o *CreateExternalDownloadDatabaseOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create external download database o k response has a 5xx status code
func (o *CreateExternalDownloadDatabaseOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create external download database o k response a status code equal to that given
func (o *CreateExternalDownloadDatabaseOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create external download database o k response
func (o *CreateExternalDownloadDatabaseOK) Code() int {
	return 200
}

func (o *CreateExternalDownloadDatabaseOK) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseOK  %+v", 200, o.Payload)
}

func (o *CreateExternalDownloadDatabaseOK) String() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseOK  %+v", 200, o.Payload)
}

func (o *CreateExternalDownloadDatabaseOK) GetPayload() *models.ExternalDownload {
	return o.Payload
}

func (o *CreateExternalDownloadDatabaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExternalDownload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateExternalDownloadDatabaseUnauthorized creates a CreateExternalDownloadDatabaseUnauthorized with default headers values
func NewCreateExternalDownloadDatabaseUnauthorized() *CreateExternalDownloadDatabaseUnauthorized {
	return &CreateExternalDownloadDatabaseUnauthorized{}
}

/*
CreateExternalDownloadDatabaseUnauthorized describes a response with status code 401, with default header values.

CreateExternalDownloadDatabaseUnauthorized create external download database unauthorized
*/
type CreateExternalDownloadDatabaseUnauthorized struct {
}

// IsSuccess returns true when this create external download database unauthorized response has a 2xx status code
func (o *CreateExternalDownloadDatabaseUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create external download database unauthorized response has a 3xx status code
func (o *CreateExternalDownloadDatabaseUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create external download database unauthorized response has a 4xx status code
func (o *CreateExternalDownloadDatabaseUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create external download database unauthorized response has a 5xx status code
func (o *CreateExternalDownloadDatabaseUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create external download database unauthorized response a status code equal to that given
func (o *CreateExternalDownloadDatabaseUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create external download database unauthorized response
func (o *CreateExternalDownloadDatabaseUnauthorized) Code() int {
	return 401
}

func (o *CreateExternalDownloadDatabaseUnauthorized) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseUnauthorized ", 401)
}

func (o *CreateExternalDownloadDatabaseUnauthorized) String() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseUnauthorized ", 401)
}

func (o *CreateExternalDownloadDatabaseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateExternalDownloadDatabaseForbidden creates a CreateExternalDownloadDatabaseForbidden with default headers values
func NewCreateExternalDownloadDatabaseForbidden() *CreateExternalDownloadDatabaseForbidden {
	return &CreateExternalDownloadDatabaseForbidden{}
}

/*
CreateExternalDownloadDatabaseForbidden describes a response with status code 403, with default header values.

CreateExternalDownloadDatabaseForbidden create external download database forbidden
*/
type CreateExternalDownloadDatabaseForbidden struct {
}

// IsSuccess returns true when this create external download database forbidden response has a 2xx status code
func (o *CreateExternalDownloadDatabaseForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create external download database forbidden response has a 3xx status code
func (o *CreateExternalDownloadDatabaseForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create external download database forbidden response has a 4xx status code
func (o *CreateExternalDownloadDatabaseForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create external download database forbidden response has a 5xx status code
func (o *CreateExternalDownloadDatabaseForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create external download database forbidden response a status code equal to that given
func (o *CreateExternalDownloadDatabaseForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create external download database forbidden response
func (o *CreateExternalDownloadDatabaseForbidden) Code() int {
	return 403
}

func (o *CreateExternalDownloadDatabaseForbidden) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseForbidden ", 403)
}

func (o *CreateExternalDownloadDatabaseForbidden) String() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseForbidden ", 403)
}

func (o *CreateExternalDownloadDatabaseForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateExternalDownloadDatabaseNotFound creates a CreateExternalDownloadDatabaseNotFound with default headers values
func NewCreateExternalDownloadDatabaseNotFound() *CreateExternalDownloadDatabaseNotFound {
	return &CreateExternalDownloadDatabaseNotFound{}
}

/*
CreateExternalDownloadDatabaseNotFound describes a response with status code 404, with default header values.

CreateExternalDownloadDatabaseNotFound create external download database not found
*/
type CreateExternalDownloadDatabaseNotFound struct {
}

// IsSuccess returns true when this create external download database not found response has a 2xx status code
func (o *CreateExternalDownloadDatabaseNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create external download database not found response has a 3xx status code
func (o *CreateExternalDownloadDatabaseNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create external download database not found response has a 4xx status code
func (o *CreateExternalDownloadDatabaseNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create external download database not found response has a 5xx status code
func (o *CreateExternalDownloadDatabaseNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create external download database not found response a status code equal to that given
func (o *CreateExternalDownloadDatabaseNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create external download database not found response
func (o *CreateExternalDownloadDatabaseNotFound) Code() int {
	return 404
}

func (o *CreateExternalDownloadDatabaseNotFound) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseNotFound ", 404)
}

func (o *CreateExternalDownloadDatabaseNotFound) String() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseNotFound ", 404)
}

func (o *CreateExternalDownloadDatabaseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateExternalDownloadDatabaseUnsupportedMediaType creates a CreateExternalDownloadDatabaseUnsupportedMediaType with default headers values
func NewCreateExternalDownloadDatabaseUnsupportedMediaType() *CreateExternalDownloadDatabaseUnsupportedMediaType {
	return &CreateExternalDownloadDatabaseUnsupportedMediaType{}
}

/*
CreateExternalDownloadDatabaseUnsupportedMediaType describes a response with status code 415, with default header values.

CreateExternalDownloadDatabaseUnsupportedMediaType create external download database unsupported media type
*/
type CreateExternalDownloadDatabaseUnsupportedMediaType struct {
}

// IsSuccess returns true when this create external download database unsupported media type response has a 2xx status code
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create external download database unsupported media type response has a 3xx status code
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create external download database unsupported media type response has a 4xx status code
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this create external download database unsupported media type response has a 5xx status code
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this create external download database unsupported media type response a status code equal to that given
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the create external download database unsupported media type response
func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) Code() int {
	return 415
}

func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseUnsupportedMediaType ", 415)
}

func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) String() string {
	return fmt.Sprintf("[POST /databases/{id}/external][%d] createExternalDownloadDatabaseUnsupportedMediaType ", 415)
}

func (o *CreateExternalDownloadDatabaseUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
