// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateExternalDownloadDatabaseParams creates a new CreateExternalDownloadDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateExternalDownloadDatabaseParams() *CreateExternalDownloadDatabaseParams {
	return &CreateExternalDownloadDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateExternalDownloadDatabaseParamsWithTimeout creates a new CreateExternalDownloadDatabaseParams object
// with the ability to set a timeout on a request.
func NewCreateExternalDownloadDatabaseParamsWithTimeout(timeout time.Duration) *CreateExternalDownloadDatabaseParams {
	return &CreateExternalDownloadDatabaseParams{
		timeout: timeout,
	}
}

// NewCreateExternalDownloadDatabaseParamsWithContext creates a new CreateExternalDownloadDatabaseParams object
// with the ability to set a context for a request.
func NewCreateExternalDownloadDatabaseParamsWithContext(ctx context.Context) *CreateExternalDownloadDatabaseParams {
	return &CreateExternalDownloadDatabaseParams{
		Context: ctx,
	}
}

// NewCreateExternalDownloadDatabaseParamsWithHTTPClient creates a new CreateExternalDownloadDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateExternalDownloadDatabaseParamsWithHTTPClient(client *http.Client) *CreateExternalDownloadDatabaseParams {
	return &CreateExternalDownloadDatabaseParams{
		HTTPClient: client,
	}
}

/*
CreateExternalDownloadDatabaseParams contains all the parameters to send to the API endpoint

	for the create external download database operation.

	Typically these are written to a http.Request.
*/
type CreateExternalDownloadDatabaseParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create external download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateExternalDownloadDatabaseParams) WithDefaults() *CreateExternalDownloadDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create external download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateExternalDownloadDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) WithTimeout(timeout time.Duration) *CreateExternalDownloadDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) WithContext(ctx context.Context) *CreateExternalDownloadDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) WithHTTPClient(client *http.Client) *CreateExternalDownloadDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) WithID(id uint64) *CreateExternalDownloadDatabaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create external download database params
func (o *CreateExternalDownloadDatabaseParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateExternalDownloadDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
