// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDatabaseByIDParams creates a new DeleteDatabaseByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDatabaseByIDParams() *DeleteDatabaseByIDParams {
	return &DeleteDatabaseByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDatabaseByIDParamsWithTimeout creates a new DeleteDatabaseByIDParams object
// with the ability to set a timeout on a request.
func NewDeleteDatabaseByIDParamsWithTimeout(timeout time.Duration) *DeleteDatabaseByIDParams {
	return &DeleteDatabaseByIDParams{
		timeout: timeout,
	}
}

// NewDeleteDatabaseByIDParamsWithContext creates a new DeleteDatabaseByIDParams object
// with the ability to set a context for a request.
func NewDeleteDatabaseByIDParamsWithContext(ctx context.Context) *DeleteDatabaseByIDParams {
	return &DeleteDatabaseByIDParams{
		Context: ctx,
	}
}

// NewDeleteDatabaseByIDParamsWithHTTPClient creates a new DeleteDatabaseByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDatabaseByIDParamsWithHTTPClient(client *http.Client) *DeleteDatabaseByIDParams {
	return &DeleteDatabaseByIDParams{
		HTTPClient: client,
	}
}

/*
DeleteDatabaseByIDParams contains all the parameters to send to the API endpoint

	for the delete database by Id operation.

	Typically these are written to a http.Request.
*/
type DeleteDatabaseByIDParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete database by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatabaseByIDParams) WithDefaults() *DeleteDatabaseByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete database by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDatabaseByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete database by Id params
func (o *DeleteDatabaseByIDParams) WithTimeout(timeout time.Duration) *DeleteDatabaseByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete database by Id params
func (o *DeleteDatabaseByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete database by Id params
func (o *DeleteDatabaseByIDParams) WithContext(ctx context.Context) *DeleteDatabaseByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete database by Id params
func (o *DeleteDatabaseByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete database by Id params
func (o *DeleteDatabaseByIDParams) WithHTTPClient(client *http.Client) *DeleteDatabaseByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete database by Id params
func (o *DeleteDatabaseByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete database by Id params
func (o *DeleteDatabaseByIDParams) WithID(id uint64) *DeleteDatabaseByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete database by Id params
func (o *DeleteDatabaseByIDParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDatabaseByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
