// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// DeployInstanceReader is a Reader for the DeployInstance structure.
type DeployInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeployInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeployInstanceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeployInstanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeployInstanceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeployInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewDeployInstanceUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeployInstanceCreated creates a DeployInstanceCreated with default headers values
func NewDeployInstanceCreated() *DeployInstanceCreated {
	return &DeployInstanceCreated{}
}

/*
DeployInstanceCreated describes a response with status code 201, with default header values.

Instance
*/
type DeployInstanceCreated struct {
	Payload *models.Instance
}

// IsSuccess returns true when this deploy instance created response has a 2xx status code
func (o *DeployInstanceCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this deploy instance created response has a 3xx status code
func (o *DeployInstanceCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deploy instance created response has a 4xx status code
func (o *DeployInstanceCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this deploy instance created response has a 5xx status code
func (o *DeployInstanceCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this deploy instance created response a status code equal to that given
func (o *DeployInstanceCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the deploy instance created response
func (o *DeployInstanceCreated) Code() int {
	return 201
}

func (o *DeployInstanceCreated) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceCreated  %+v", 201, o.Payload)
}

func (o *DeployInstanceCreated) String() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceCreated  %+v", 201, o.Payload)
}

func (o *DeployInstanceCreated) GetPayload() *models.Instance {
	return o.Payload
}

func (o *DeployInstanceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Instance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeployInstanceUnauthorized creates a DeployInstanceUnauthorized with default headers values
func NewDeployInstanceUnauthorized() *DeployInstanceUnauthorized {
	return &DeployInstanceUnauthorized{}
}

/*
DeployInstanceUnauthorized describes a response with status code 401, with default header values.

DeployInstanceUnauthorized deploy instance unauthorized
*/
type DeployInstanceUnauthorized struct {
}

// IsSuccess returns true when this deploy instance unauthorized response has a 2xx status code
func (o *DeployInstanceUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this deploy instance unauthorized response has a 3xx status code
func (o *DeployInstanceUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deploy instance unauthorized response has a 4xx status code
func (o *DeployInstanceUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this deploy instance unauthorized response has a 5xx status code
func (o *DeployInstanceUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this deploy instance unauthorized response a status code equal to that given
func (o *DeployInstanceUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the deploy instance unauthorized response
func (o *DeployInstanceUnauthorized) Code() int {
	return 401
}

func (o *DeployInstanceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnauthorized ", 401)
}

func (o *DeployInstanceUnauthorized) String() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnauthorized ", 401)
}

func (o *DeployInstanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceForbidden creates a DeployInstanceForbidden with default headers values
func NewDeployInstanceForbidden() *DeployInstanceForbidden {
	return &DeployInstanceForbidden{}
}

/*
DeployInstanceForbidden describes a response with status code 403, with default header values.

DeployInstanceForbidden deploy instance forbidden
*/
type DeployInstanceForbidden struct {
}

// IsSuccess returns true when this deploy instance forbidden response has a 2xx status code
func (o *DeployInstanceForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this deploy instance forbidden response has a 3xx status code
func (o *DeployInstanceForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deploy instance forbidden response has a 4xx status code
func (o *DeployInstanceForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this deploy instance forbidden response has a 5xx status code
func (o *DeployInstanceForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this deploy instance forbidden response a status code equal to that given
func (o *DeployInstanceForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the deploy instance forbidden response
func (o *DeployInstanceForbidden) Code() int {
	return 403
}

func (o *DeployInstanceForbidden) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceForbidden ", 403)
}

func (o *DeployInstanceForbidden) String() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceForbidden ", 403)
}

func (o *DeployInstanceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceNotFound creates a DeployInstanceNotFound with default headers values
func NewDeployInstanceNotFound() *DeployInstanceNotFound {
	return &DeployInstanceNotFound{}
}

/*
DeployInstanceNotFound describes a response with status code 404, with default header values.

DeployInstanceNotFound deploy instance not found
*/
type DeployInstanceNotFound struct {
}

// IsSuccess returns true when this deploy instance not found response has a 2xx status code
func (o *DeployInstanceNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this deploy instance not found response has a 3xx status code
func (o *DeployInstanceNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deploy instance not found response has a 4xx status code
func (o *DeployInstanceNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this deploy instance not found response has a 5xx status code
func (o *DeployInstanceNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this deploy instance not found response a status code equal to that given
func (o *DeployInstanceNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the deploy instance not found response
func (o *DeployInstanceNotFound) Code() int {
	return 404
}

func (o *DeployInstanceNotFound) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceNotFound ", 404)
}

func (o *DeployInstanceNotFound) String() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceNotFound ", 404)
}

func (o *DeployInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceUnsupportedMediaType creates a DeployInstanceUnsupportedMediaType with default headers values
func NewDeployInstanceUnsupportedMediaType() *DeployInstanceUnsupportedMediaType {
	return &DeployInstanceUnsupportedMediaType{}
}

/*
DeployInstanceUnsupportedMediaType describes a response with status code 415, with default header values.

DeployInstanceUnsupportedMediaType deploy instance unsupported media type
*/
type DeployInstanceUnsupportedMediaType struct {
}

// IsSuccess returns true when this deploy instance unsupported media type response has a 2xx status code
func (o *DeployInstanceUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this deploy instance unsupported media type response has a 3xx status code
func (o *DeployInstanceUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this deploy instance unsupported media type response has a 4xx status code
func (o *DeployInstanceUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this deploy instance unsupported media type response has a 5xx status code
func (o *DeployInstanceUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this deploy instance unsupported media type response a status code equal to that given
func (o *DeployInstanceUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the deploy instance unsupported media type response
func (o *DeployInstanceUnsupportedMediaType) Code() int {
	return 415
}

func (o *DeployInstanceUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnsupportedMediaType ", 415)
}

func (o *DeployInstanceUnsupportedMediaType) String() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnsupportedMediaType ", 415)
}

func (o *DeployInstanceUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
