// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// DeployInstanceReader is a Reader for the DeployInstance structure.
type DeployInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeployInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeployInstanceCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeployInstanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeployInstanceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeployInstanceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewDeployInstanceUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeployInstanceCreated creates a DeployInstanceCreated with default headers values
func NewDeployInstanceCreated() *DeployInstanceCreated {
	return &DeployInstanceCreated{}
}

/* DeployInstanceCreated describes a response with status code 201, with default header values.

Instance
*/
type DeployInstanceCreated struct {
	Payload *models.Instance
}

func (o *DeployInstanceCreated) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceCreated  %+v", 201, o.Payload)
}
func (o *DeployInstanceCreated) GetPayload() *models.Instance {
	return o.Payload
}

func (o *DeployInstanceCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Instance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeployInstanceUnauthorized creates a DeployInstanceUnauthorized with default headers values
func NewDeployInstanceUnauthorized() *DeployInstanceUnauthorized {
	return &DeployInstanceUnauthorized{}
}

/* DeployInstanceUnauthorized describes a response with status code 401, with default header values.

DeployInstanceUnauthorized deploy instance unauthorized
*/
type DeployInstanceUnauthorized struct {
}

func (o *DeployInstanceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnauthorized ", 401)
}

func (o *DeployInstanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceForbidden creates a DeployInstanceForbidden with default headers values
func NewDeployInstanceForbidden() *DeployInstanceForbidden {
	return &DeployInstanceForbidden{}
}

/* DeployInstanceForbidden describes a response with status code 403, with default header values.

DeployInstanceForbidden deploy instance forbidden
*/
type DeployInstanceForbidden struct {
}

func (o *DeployInstanceForbidden) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceForbidden ", 403)
}

func (o *DeployInstanceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceNotFound creates a DeployInstanceNotFound with default headers values
func NewDeployInstanceNotFound() *DeployInstanceNotFound {
	return &DeployInstanceNotFound{}
}

/* DeployInstanceNotFound describes a response with status code 404, with default header values.

DeployInstanceNotFound deploy instance not found
*/
type DeployInstanceNotFound struct {
}

func (o *DeployInstanceNotFound) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceNotFound ", 404)
}

func (o *DeployInstanceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeployInstanceUnsupportedMediaType creates a DeployInstanceUnsupportedMediaType with default headers values
func NewDeployInstanceUnsupportedMediaType() *DeployInstanceUnsupportedMediaType {
	return &DeployInstanceUnsupportedMediaType{}
}

/* DeployInstanceUnsupportedMediaType describes a response with status code 415, with default header values.

DeployInstanceUnsupportedMediaType deploy instance unsupported media type
*/
type DeployInstanceUnsupportedMediaType struct {
}

func (o *DeployInstanceUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /instances][%d] deployInstanceUnsupportedMediaType ", 415)
}

func (o *DeployInstanceUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
