// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDownloadDatabaseParams creates a new DownloadDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDownloadDatabaseParams() *DownloadDatabaseParams {
	return &DownloadDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDownloadDatabaseParamsWithTimeout creates a new DownloadDatabaseParams object
// with the ability to set a timeout on a request.
func NewDownloadDatabaseParamsWithTimeout(timeout time.Duration) *DownloadDatabaseParams {
	return &DownloadDatabaseParams{
		timeout: timeout,
	}
}

// NewDownloadDatabaseParamsWithContext creates a new DownloadDatabaseParams object
// with the ability to set a context for a request.
func NewDownloadDatabaseParamsWithContext(ctx context.Context) *DownloadDatabaseParams {
	return &DownloadDatabaseParams{
		Context: ctx,
	}
}

// NewDownloadDatabaseParamsWithHTTPClient creates a new DownloadDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewDownloadDatabaseParamsWithHTTPClient(client *http.Client) *DownloadDatabaseParams {
	return &DownloadDatabaseParams{
		HTTPClient: client,
	}
}

/*
DownloadDatabaseParams contains all the parameters to send to the API endpoint

	for the download database operation.

	Typically these are written to a http.Request.
*/
type DownloadDatabaseParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadDatabaseParams) WithDefaults() *DownloadDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DownloadDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the download database params
func (o *DownloadDatabaseParams) WithTimeout(timeout time.Duration) *DownloadDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the download database params
func (o *DownloadDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the download database params
func (o *DownloadDatabaseParams) WithContext(ctx context.Context) *DownloadDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the download database params
func (o *DownloadDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the download database params
func (o *DownloadDatabaseParams) WithHTTPClient(client *http.Client) *DownloadDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the download database params
func (o *DownloadDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the download database params
func (o *DownloadDatabaseParams) WithID(id uint64) *DownloadDatabaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the download database params
func (o *DownloadDatabaseParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DownloadDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
