// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewExternalDownloadDatabaseParams creates a new ExternalDownloadDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExternalDownloadDatabaseParams() *ExternalDownloadDatabaseParams {
	return &ExternalDownloadDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExternalDownloadDatabaseParamsWithTimeout creates a new ExternalDownloadDatabaseParams object
// with the ability to set a timeout on a request.
func NewExternalDownloadDatabaseParamsWithTimeout(timeout time.Duration) *ExternalDownloadDatabaseParams {
	return &ExternalDownloadDatabaseParams{
		timeout: timeout,
	}
}

// NewExternalDownloadDatabaseParamsWithContext creates a new ExternalDownloadDatabaseParams object
// with the ability to set a context for a request.
func NewExternalDownloadDatabaseParamsWithContext(ctx context.Context) *ExternalDownloadDatabaseParams {
	return &ExternalDownloadDatabaseParams{
		Context: ctx,
	}
}

// NewExternalDownloadDatabaseParamsWithHTTPClient creates a new ExternalDownloadDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewExternalDownloadDatabaseParamsWithHTTPClient(client *http.Client) *ExternalDownloadDatabaseParams {
	return &ExternalDownloadDatabaseParams{
		HTTPClient: client,
	}
}

/*
ExternalDownloadDatabaseParams contains all the parameters to send to the API endpoint

	for the external download database operation.

	Typically these are written to a http.Request.
*/
type ExternalDownloadDatabaseParams struct {

	// UUID.
	//
	// Format: uint64
	UUID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the external download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalDownloadDatabaseParams) WithDefaults() *ExternalDownloadDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the external download database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExternalDownloadDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the external download database params
func (o *ExternalDownloadDatabaseParams) WithTimeout(timeout time.Duration) *ExternalDownloadDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the external download database params
func (o *ExternalDownloadDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the external download database params
func (o *ExternalDownloadDatabaseParams) WithContext(ctx context.Context) *ExternalDownloadDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the external download database params
func (o *ExternalDownloadDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the external download database params
func (o *ExternalDownloadDatabaseParams) WithHTTPClient(client *http.Client) *ExternalDownloadDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the external download database params
func (o *ExternalDownloadDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the external download database params
func (o *ExternalDownloadDatabaseParams) WithUUID(uuid uint64) *ExternalDownloadDatabaseParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the external download database params
func (o *ExternalDownloadDatabaseParams) SetUUID(uuid uint64) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ExternalDownloadDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", swag.FormatUint64(o.UUID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
