// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// FindByIDDecryptedReader is a Reader for the FindByIDDecrypted structure.
type FindByIDDecryptedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindByIDDecryptedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindByIDDecryptedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewFindByIDDecryptedUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewFindByIDDecryptedForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewFindByIDDecryptedNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewFindByIDDecryptedUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFindByIDDecryptedOK creates a FindByIDDecryptedOK with default headers values
func NewFindByIDDecryptedOK() *FindByIDDecryptedOK {
	return &FindByIDDecryptedOK{}
}

/* FindByIDDecryptedOK describes a response with status code 200, with default header values.

Instance
*/
type FindByIDDecryptedOK struct {
	Payload *models.Instance
}

func (o *FindByIDDecryptedOK) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/parameters][%d] findByIdDecryptedOK  %+v", 200, o.Payload)
}
func (o *FindByIDDecryptedOK) GetPayload() *models.Instance {
	return o.Payload
}

func (o *FindByIDDecryptedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Instance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindByIDDecryptedUnauthorized creates a FindByIDDecryptedUnauthorized with default headers values
func NewFindByIDDecryptedUnauthorized() *FindByIDDecryptedUnauthorized {
	return &FindByIDDecryptedUnauthorized{}
}

/* FindByIDDecryptedUnauthorized describes a response with status code 401, with default header values.

FindByIDDecryptedUnauthorized find by Id decrypted unauthorized
*/
type FindByIDDecryptedUnauthorized struct {
}

func (o *FindByIDDecryptedUnauthorized) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/parameters][%d] findByIdDecryptedUnauthorized ", 401)
}

func (o *FindByIDDecryptedUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindByIDDecryptedForbidden creates a FindByIDDecryptedForbidden with default headers values
func NewFindByIDDecryptedForbidden() *FindByIDDecryptedForbidden {
	return &FindByIDDecryptedForbidden{}
}

/* FindByIDDecryptedForbidden describes a response with status code 403, with default header values.

FindByIDDecryptedForbidden find by Id decrypted forbidden
*/
type FindByIDDecryptedForbidden struct {
}

func (o *FindByIDDecryptedForbidden) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/parameters][%d] findByIdDecryptedForbidden ", 403)
}

func (o *FindByIDDecryptedForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindByIDDecryptedNotFound creates a FindByIDDecryptedNotFound with default headers values
func NewFindByIDDecryptedNotFound() *FindByIDDecryptedNotFound {
	return &FindByIDDecryptedNotFound{}
}

/* FindByIDDecryptedNotFound describes a response with status code 404, with default header values.

FindByIDDecryptedNotFound find by Id decrypted not found
*/
type FindByIDDecryptedNotFound struct {
}

func (o *FindByIDDecryptedNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/parameters][%d] findByIdDecryptedNotFound ", 404)
}

func (o *FindByIDDecryptedNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFindByIDDecryptedUnsupportedMediaType creates a FindByIDDecryptedUnsupportedMediaType with default headers values
func NewFindByIDDecryptedUnsupportedMediaType() *FindByIDDecryptedUnsupportedMediaType {
	return &FindByIDDecryptedUnsupportedMediaType{}
}

/* FindByIDDecryptedUnsupportedMediaType describes a response with status code 415, with default header values.

FindByIDDecryptedUnsupportedMediaType find by Id decrypted unsupported media type
*/
type FindByIDDecryptedUnsupportedMediaType struct {
}

func (o *FindByIDDecryptedUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/parameters][%d] findByIdDecryptedUnsupportedMediaType ", 415)
}

func (o *FindByIDDecryptedUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
