// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindDatabaseParams creates a new FindDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindDatabaseParams() *FindDatabaseParams {
	return &FindDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindDatabaseParamsWithTimeout creates a new FindDatabaseParams object
// with the ability to set a timeout on a request.
func NewFindDatabaseParamsWithTimeout(timeout time.Duration) *FindDatabaseParams {
	return &FindDatabaseParams{
		timeout: timeout,
	}
}

// NewFindDatabaseParamsWithContext creates a new FindDatabaseParams object
// with the ability to set a context for a request.
func NewFindDatabaseParamsWithContext(ctx context.Context) *FindDatabaseParams {
	return &FindDatabaseParams{
		Context: ctx,
	}
}

// NewFindDatabaseParamsWithHTTPClient creates a new FindDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindDatabaseParamsWithHTTPClient(client *http.Client) *FindDatabaseParams {
	return &FindDatabaseParams{
		HTTPClient: client,
	}
}

/*
FindDatabaseParams contains all the parameters to send to the API endpoint

	for the find database operation.

	Typically these are written to a http.Request.
*/
type FindDatabaseParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindDatabaseParams) WithDefaults() *FindDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find database params
func (o *FindDatabaseParams) WithTimeout(timeout time.Duration) *FindDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find database params
func (o *FindDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find database params
func (o *FindDatabaseParams) WithContext(ctx context.Context) *FindDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find database params
func (o *FindDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find database params
func (o *FindDatabaseParams) WithHTTPClient(client *http.Client) *FindDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find database params
func (o *FindDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find database params
func (o *FindDatabaseParams) WithID(id uint64) *FindDatabaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find database params
func (o *FindDatabaseParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
