// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindByIDDecryptedParams creates a new FindByIDDecryptedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindByIDDecryptedParams() *FindByIDDecryptedParams {
	return &FindByIDDecryptedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindByIDDecryptedParamsWithTimeout creates a new FindByIDDecryptedParams object
// with the ability to set a timeout on a request.
func NewFindByIDDecryptedParamsWithTimeout(timeout time.Duration) *FindByIDDecryptedParams {
	return &FindByIDDecryptedParams{
		timeout: timeout,
	}
}

// NewFindByIDDecryptedParamsWithContext creates a new FindByIDDecryptedParams object
// with the ability to set a context for a request.
func NewFindByIDDecryptedParamsWithContext(ctx context.Context) *FindByIDDecryptedParams {
	return &FindByIDDecryptedParams{
		Context: ctx,
	}
}

// NewFindByIDDecryptedParamsWithHTTPClient creates a new FindByIDDecryptedParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindByIDDecryptedParamsWithHTTPClient(client *http.Client) *FindByIDDecryptedParams {
	return &FindByIDDecryptedParams{
		HTTPClient: client,
	}
}

/*
FindByIDDecryptedParams contains all the parameters to send to the API endpoint

	for the find by Id decrypted operation.

	Typically these are written to a http.Request.
*/
type FindByIDDecryptedParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find by Id decrypted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindByIDDecryptedParams) WithDefaults() *FindByIDDecryptedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find by Id decrypted params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindByIDDecryptedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find by Id decrypted params
func (o *FindByIDDecryptedParams) WithTimeout(timeout time.Duration) *FindByIDDecryptedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find by Id decrypted params
func (o *FindByIDDecryptedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find by Id decrypted params
func (o *FindByIDDecryptedParams) WithContext(ctx context.Context) *FindByIDDecryptedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find by Id decrypted params
func (o *FindByIDDecryptedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find by Id decrypted params
func (o *FindByIDDecryptedParams) WithHTTPClient(client *http.Client) *FindByIDDecryptedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find by Id decrypted params
func (o *FindByIDDecryptedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find by Id decrypted params
func (o *FindByIDDecryptedParams) WithID(id uint64) *FindByIDDecryptedParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find by Id decrypted params
func (o *FindByIDDecryptedParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindByIDDecryptedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
