// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindByIDParams creates a new FindByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindByIDParams() *FindByIDParams {
	return &FindByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindByIDParamsWithTimeout creates a new FindByIDParams object
// with the ability to set a timeout on a request.
func NewFindByIDParamsWithTimeout(timeout time.Duration) *FindByIDParams {
	return &FindByIDParams{
		timeout: timeout,
	}
}

// NewFindByIDParamsWithContext creates a new FindByIDParams object
// with the ability to set a context for a request.
func NewFindByIDParamsWithContext(ctx context.Context) *FindByIDParams {
	return &FindByIDParams{
		Context: ctx,
	}
}

// NewFindByIDParamsWithHTTPClient creates a new FindByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindByIDParamsWithHTTPClient(client *http.Client) *FindByIDParams {
	return &FindByIDParams{
		HTTPClient: client,
	}
}

/* FindByIDParams contains all the parameters to send to the API endpoint
   for the find by Id operation.

   Typically these are written to a http.Request.
*/
type FindByIDParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindByIDParams) WithDefaults() *FindByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find by Id params
func (o *FindByIDParams) WithTimeout(timeout time.Duration) *FindByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find by Id params
func (o *FindByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find by Id params
func (o *FindByIDParams) WithContext(ctx context.Context) *FindByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find by Id params
func (o *FindByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find by Id params
func (o *FindByIDParams) WithHTTPClient(client *http.Client) *FindByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find by Id params
func (o *FindByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find by Id params
func (o *FindByIDParams) WithID(id uint64) *FindByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find by Id params
func (o *FindByIDParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
