// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// InstanceLogsReader is a Reader for the InstanceLogs structure.
type InstanceLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InstanceLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInstanceLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewInstanceLogsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewInstanceLogsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewInstanceLogsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewInstanceLogsUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewInstanceLogsOK creates a InstanceLogsOK with default headers values
func NewInstanceLogsOK() *InstanceLogsOK {
	return &InstanceLogsOK{}
}

/* InstanceLogsOK describes a response with status code 200, with default header values.

InstanceLogsOK instance logs o k
*/
type InstanceLogsOK struct {
}

// IsSuccess returns true when this instance logs o k response has a 2xx status code
func (o *InstanceLogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this instance logs o k response has a 3xx status code
func (o *InstanceLogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance logs o k response has a 4xx status code
func (o *InstanceLogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this instance logs o k response has a 5xx status code
func (o *InstanceLogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this instance logs o k response a status code equal to that given
func (o *InstanceLogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the instance logs o k response
func (o *InstanceLogsOK) Code() int {
	return 200
}

func (o *InstanceLogsOK) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsOK ", 200)
}

func (o *InstanceLogsOK) String() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsOK ", 200)
}

func (o *InstanceLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceLogsUnauthorized creates a InstanceLogsUnauthorized with default headers values
func NewInstanceLogsUnauthorized() *InstanceLogsUnauthorized {
	return &InstanceLogsUnauthorized{}
}

/* InstanceLogsUnauthorized describes a response with status code 401, with default header values.

InstanceLogsUnauthorized instance logs unauthorized
*/
type InstanceLogsUnauthorized struct {
}

// IsSuccess returns true when this instance logs unauthorized response has a 2xx status code
func (o *InstanceLogsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance logs unauthorized response has a 3xx status code
func (o *InstanceLogsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance logs unauthorized response has a 4xx status code
func (o *InstanceLogsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance logs unauthorized response has a 5xx status code
func (o *InstanceLogsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this instance logs unauthorized response a status code equal to that given
func (o *InstanceLogsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the instance logs unauthorized response
func (o *InstanceLogsUnauthorized) Code() int {
	return 401
}

func (o *InstanceLogsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsUnauthorized ", 401)
}

func (o *InstanceLogsUnauthorized) String() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsUnauthorized ", 401)
}

func (o *InstanceLogsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceLogsForbidden creates a InstanceLogsForbidden with default headers values
func NewInstanceLogsForbidden() *InstanceLogsForbidden {
	return &InstanceLogsForbidden{}
}

/* InstanceLogsForbidden describes a response with status code 403, with default header values.

InstanceLogsForbidden instance logs forbidden
*/
type InstanceLogsForbidden struct {
}

// IsSuccess returns true when this instance logs forbidden response has a 2xx status code
func (o *InstanceLogsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance logs forbidden response has a 3xx status code
func (o *InstanceLogsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance logs forbidden response has a 4xx status code
func (o *InstanceLogsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance logs forbidden response has a 5xx status code
func (o *InstanceLogsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this instance logs forbidden response a status code equal to that given
func (o *InstanceLogsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the instance logs forbidden response
func (o *InstanceLogsForbidden) Code() int {
	return 403
}

func (o *InstanceLogsForbidden) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsForbidden ", 403)
}

func (o *InstanceLogsForbidden) String() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsForbidden ", 403)
}

func (o *InstanceLogsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceLogsNotFound creates a InstanceLogsNotFound with default headers values
func NewInstanceLogsNotFound() *InstanceLogsNotFound {
	return &InstanceLogsNotFound{}
}

/* InstanceLogsNotFound describes a response with status code 404, with default header values.

InstanceLogsNotFound instance logs not found
*/
type InstanceLogsNotFound struct {
}

// IsSuccess returns true when this instance logs not found response has a 2xx status code
func (o *InstanceLogsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance logs not found response has a 3xx status code
func (o *InstanceLogsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance logs not found response has a 4xx status code
func (o *InstanceLogsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance logs not found response has a 5xx status code
func (o *InstanceLogsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this instance logs not found response a status code equal to that given
func (o *InstanceLogsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the instance logs not found response
func (o *InstanceLogsNotFound) Code() int {
	return 404
}

func (o *InstanceLogsNotFound) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsNotFound ", 404)
}

func (o *InstanceLogsNotFound) String() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsNotFound ", 404)
}

func (o *InstanceLogsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInstanceLogsUnsupportedMediaType creates a InstanceLogsUnsupportedMediaType with default headers values
func NewInstanceLogsUnsupportedMediaType() *InstanceLogsUnsupportedMediaType {
	return &InstanceLogsUnsupportedMediaType{}
}

/* InstanceLogsUnsupportedMediaType describes a response with status code 415, with default header values.

InstanceLogsUnsupportedMediaType instance logs unsupported media type
*/
type InstanceLogsUnsupportedMediaType struct {
}

// IsSuccess returns true when this instance logs unsupported media type response has a 2xx status code
func (o *InstanceLogsUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this instance logs unsupported media type response has a 3xx status code
func (o *InstanceLogsUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this instance logs unsupported media type response has a 4xx status code
func (o *InstanceLogsUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this instance logs unsupported media type response has a 5xx status code
func (o *InstanceLogsUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this instance logs unsupported media type response a status code equal to that given
func (o *InstanceLogsUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the instance logs unsupported media type response
func (o *InstanceLogsUnsupportedMediaType) Code() int {
	return 415
}

func (o *InstanceLogsUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsUnsupportedMediaType ", 415)
}

func (o *InstanceLogsUnsupportedMediaType) String() string {
	return fmt.Sprintf("[GET /instances/{id}/logs][%d] instanceLogsUnsupportedMediaType ", 415)
}

func (o *InstanceLogsUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
