// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// ListInstancesReader is a Reader for the ListInstances structure.
type ListInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListInstancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListInstancesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListInstancesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewListInstancesUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListInstancesOK creates a ListInstancesOK with default headers values
func NewListInstancesOK() *ListInstancesOK {
	return &ListInstancesOK{}
}

/* ListInstancesOK describes a response with status code 200, with default header values.

GroupWithInstances
*/
type ListInstancesOK struct {
	Payload []*models.GroupWithInstances
}

func (o *ListInstancesOK) Error() string {
	return fmt.Sprintf("[GET /instances][%d] listInstancesOK  %+v", 200, o.Payload)
}
func (o *ListInstancesOK) GetPayload() []*models.GroupWithInstances {
	return o.Payload
}

func (o *ListInstancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListInstancesUnauthorized creates a ListInstancesUnauthorized with default headers values
func NewListInstancesUnauthorized() *ListInstancesUnauthorized {
	return &ListInstancesUnauthorized{}
}

/* ListInstancesUnauthorized describes a response with status code 401, with default header values.

ListInstancesUnauthorized list instances unauthorized
*/
type ListInstancesUnauthorized struct {
}

func (o *ListInstancesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /instances][%d] listInstancesUnauthorized ", 401)
}

func (o *ListInstancesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstancesForbidden creates a ListInstancesForbidden with default headers values
func NewListInstancesForbidden() *ListInstancesForbidden {
	return &ListInstancesForbidden{}
}

/* ListInstancesForbidden describes a response with status code 403, with default header values.

ListInstancesForbidden list instances forbidden
*/
type ListInstancesForbidden struct {
}

func (o *ListInstancesForbidden) Error() string {
	return fmt.Sprintf("[GET /instances][%d] listInstancesForbidden ", 403)
}

func (o *ListInstancesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListInstancesUnsupportedMediaType creates a ListInstancesUnsupportedMediaType with default headers values
func NewListInstancesUnsupportedMediaType() *ListInstancesUnsupportedMediaType {
	return &ListInstancesUnsupportedMediaType{}
}

/* ListInstancesUnsupportedMediaType describes a response with status code 415, with default header values.

ListInstancesUnsupportedMediaType list instances unsupported media type
*/
type ListInstancesUnsupportedMediaType struct {
}

func (o *ListInstancesUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[GET /instances][%d] listInstancesUnsupportedMediaType ", 415)
}

func (o *ListInstancesUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
