// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// LockDatabaseByIDReader is a Reader for the LockDatabaseByID structure.
type LockDatabaseByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LockDatabaseByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLockDatabaseByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewLockDatabaseByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewLockDatabaseByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewLockDatabaseByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewLockDatabaseByIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewLockDatabaseByIDUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLockDatabaseByIDOK creates a LockDatabaseByIDOK with default headers values
func NewLockDatabaseByIDOK() *LockDatabaseByIDOK {
	return &LockDatabaseByIDOK{}
}

/*
LockDatabaseByIDOK describes a response with status code 200, with default header values.

LockDatabaseByIDOK lock database by Id o k
*/
type LockDatabaseByIDOK struct {
	Payload *models.Lock
}

// IsSuccess returns true when this lock database by Id o k response has a 2xx status code
func (o *LockDatabaseByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this lock database by Id o k response has a 3xx status code
func (o *LockDatabaseByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id o k response has a 4xx status code
func (o *LockDatabaseByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this lock database by Id o k response has a 5xx status code
func (o *LockDatabaseByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id o k response a status code equal to that given
func (o *LockDatabaseByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the lock database by Id o k response
func (o *LockDatabaseByIDOK) Code() int {
	return 200
}

func (o *LockDatabaseByIDOK) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdOK  %+v", 200, o.Payload)
}

func (o *LockDatabaseByIDOK) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdOK  %+v", 200, o.Payload)
}

func (o *LockDatabaseByIDOK) GetPayload() *models.Lock {
	return o.Payload
}

func (o *LockDatabaseByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Lock)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLockDatabaseByIDUnauthorized creates a LockDatabaseByIDUnauthorized with default headers values
func NewLockDatabaseByIDUnauthorized() *LockDatabaseByIDUnauthorized {
	return &LockDatabaseByIDUnauthorized{}
}

/*
LockDatabaseByIDUnauthorized describes a response with status code 401, with default header values.

LockDatabaseByIDUnauthorized lock database by Id unauthorized
*/
type LockDatabaseByIDUnauthorized struct {
}

// IsSuccess returns true when this lock database by Id unauthorized response has a 2xx status code
func (o *LockDatabaseByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock database by Id unauthorized response has a 3xx status code
func (o *LockDatabaseByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id unauthorized response has a 4xx status code
func (o *LockDatabaseByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock database by Id unauthorized response has a 5xx status code
func (o *LockDatabaseByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id unauthorized response a status code equal to that given
func (o *LockDatabaseByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the lock database by Id unauthorized response
func (o *LockDatabaseByIDUnauthorized) Code() int {
	return 401
}

func (o *LockDatabaseByIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdUnauthorized ", 401)
}

func (o *LockDatabaseByIDUnauthorized) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdUnauthorized ", 401)
}

func (o *LockDatabaseByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLockDatabaseByIDForbidden creates a LockDatabaseByIDForbidden with default headers values
func NewLockDatabaseByIDForbidden() *LockDatabaseByIDForbidden {
	return &LockDatabaseByIDForbidden{}
}

/*
LockDatabaseByIDForbidden describes a response with status code 403, with default header values.

LockDatabaseByIDForbidden lock database by Id forbidden
*/
type LockDatabaseByIDForbidden struct {
}

// IsSuccess returns true when this lock database by Id forbidden response has a 2xx status code
func (o *LockDatabaseByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock database by Id forbidden response has a 3xx status code
func (o *LockDatabaseByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id forbidden response has a 4xx status code
func (o *LockDatabaseByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock database by Id forbidden response has a 5xx status code
func (o *LockDatabaseByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id forbidden response a status code equal to that given
func (o *LockDatabaseByIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the lock database by Id forbidden response
func (o *LockDatabaseByIDForbidden) Code() int {
	return 403
}

func (o *LockDatabaseByIDForbidden) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdForbidden ", 403)
}

func (o *LockDatabaseByIDForbidden) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdForbidden ", 403)
}

func (o *LockDatabaseByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLockDatabaseByIDNotFound creates a LockDatabaseByIDNotFound with default headers values
func NewLockDatabaseByIDNotFound() *LockDatabaseByIDNotFound {
	return &LockDatabaseByIDNotFound{}
}

/*
LockDatabaseByIDNotFound describes a response with status code 404, with default header values.

LockDatabaseByIDNotFound lock database by Id not found
*/
type LockDatabaseByIDNotFound struct {
}

// IsSuccess returns true when this lock database by Id not found response has a 2xx status code
func (o *LockDatabaseByIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock database by Id not found response has a 3xx status code
func (o *LockDatabaseByIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id not found response has a 4xx status code
func (o *LockDatabaseByIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock database by Id not found response has a 5xx status code
func (o *LockDatabaseByIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id not found response a status code equal to that given
func (o *LockDatabaseByIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the lock database by Id not found response
func (o *LockDatabaseByIDNotFound) Code() int {
	return 404
}

func (o *LockDatabaseByIDNotFound) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdNotFound ", 404)
}

func (o *LockDatabaseByIDNotFound) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdNotFound ", 404)
}

func (o *LockDatabaseByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLockDatabaseByIDConflict creates a LockDatabaseByIDConflict with default headers values
func NewLockDatabaseByIDConflict() *LockDatabaseByIDConflict {
	return &LockDatabaseByIDConflict{}
}

/*
LockDatabaseByIDConflict describes a response with status code 409, with default header values.

LockDatabaseByIDConflict lock database by Id conflict
*/
type LockDatabaseByIDConflict struct {
}

// IsSuccess returns true when this lock database by Id conflict response has a 2xx status code
func (o *LockDatabaseByIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock database by Id conflict response has a 3xx status code
func (o *LockDatabaseByIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id conflict response has a 4xx status code
func (o *LockDatabaseByIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock database by Id conflict response has a 5xx status code
func (o *LockDatabaseByIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id conflict response a status code equal to that given
func (o *LockDatabaseByIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the lock database by Id conflict response
func (o *LockDatabaseByIDConflict) Code() int {
	return 409
}

func (o *LockDatabaseByIDConflict) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdConflict ", 409)
}

func (o *LockDatabaseByIDConflict) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdConflict ", 409)
}

func (o *LockDatabaseByIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLockDatabaseByIDUnsupportedMediaType creates a LockDatabaseByIDUnsupportedMediaType with default headers values
func NewLockDatabaseByIDUnsupportedMediaType() *LockDatabaseByIDUnsupportedMediaType {
	return &LockDatabaseByIDUnsupportedMediaType{}
}

/*
LockDatabaseByIDUnsupportedMediaType describes a response with status code 415, with default header values.

LockDatabaseByIDUnsupportedMediaType lock database by Id unsupported media type
*/
type LockDatabaseByIDUnsupportedMediaType struct {
}

// IsSuccess returns true when this lock database by Id unsupported media type response has a 2xx status code
func (o *LockDatabaseByIDUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this lock database by Id unsupported media type response has a 3xx status code
func (o *LockDatabaseByIDUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this lock database by Id unsupported media type response has a 4xx status code
func (o *LockDatabaseByIDUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this lock database by Id unsupported media type response has a 5xx status code
func (o *LockDatabaseByIDUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this lock database by Id unsupported media type response a status code equal to that given
func (o *LockDatabaseByIDUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the lock database by Id unsupported media type response
func (o *LockDatabaseByIDUnsupportedMediaType) Code() int {
	return 415
}

func (o *LockDatabaseByIDUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdUnsupportedMediaType ", 415)
}

func (o *LockDatabaseByIDUnsupportedMediaType) String() string {
	return fmt.Sprintf("[POST /databases/{id}/lock][%d] lockDatabaseByIdUnsupportedMediaType ", 415)
}

func (o *LockDatabaseByIDUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
