// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPauseInstanceParams creates a new PauseInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPauseInstanceParams() *PauseInstanceParams {
	return &PauseInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPauseInstanceParamsWithTimeout creates a new PauseInstanceParams object
// with the ability to set a timeout on a request.
func NewPauseInstanceParamsWithTimeout(timeout time.Duration) *PauseInstanceParams {
	return &PauseInstanceParams{
		timeout: timeout,
	}
}

// NewPauseInstanceParamsWithContext creates a new PauseInstanceParams object
// with the ability to set a context for a request.
func NewPauseInstanceParamsWithContext(ctx context.Context) *PauseInstanceParams {
	return &PauseInstanceParams{
		Context: ctx,
	}
}

// NewPauseInstanceParamsWithHTTPClient creates a new PauseInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPauseInstanceParamsWithHTTPClient(client *http.Client) *PauseInstanceParams {
	return &PauseInstanceParams{
		HTTPClient: client,
	}
}

/* PauseInstanceParams contains all the parameters to send to the API endpoint
   for the pause instance operation.

   Typically these are written to a http.Request.
*/
type PauseInstanceParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pause instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseInstanceParams) WithDefaults() *PauseInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pause instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PauseInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pause instance params
func (o *PauseInstanceParams) WithTimeout(timeout time.Duration) *PauseInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pause instance params
func (o *PauseInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pause instance params
func (o *PauseInstanceParams) WithContext(ctx context.Context) *PauseInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pause instance params
func (o *PauseInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pause instance params
func (o *PauseInstanceParams) WithHTTPClient(client *http.Client) *PauseInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pause instance params
func (o *PauseInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pause instance params
func (o *PauseInstanceParams) WithID(id uint64) *PauseInstanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pause instance params
func (o *PauseInstanceParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PauseInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
