// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostIntegrationParams creates a new PostIntegrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostIntegrationParams() *PostIntegrationParams {
	return &PostIntegrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostIntegrationParamsWithTimeout creates a new PostIntegrationParams object
// with the ability to set a timeout on a request.
func NewPostIntegrationParamsWithTimeout(timeout time.Duration) *PostIntegrationParams {
	return &PostIntegrationParams{
		timeout: timeout,
	}
}

// NewPostIntegrationParamsWithContext creates a new PostIntegrationParams object
// with the ability to set a context for a request.
func NewPostIntegrationParamsWithContext(ctx context.Context) *PostIntegrationParams {
	return &PostIntegrationParams{
		Context: ctx,
	}
}

// NewPostIntegrationParamsWithHTTPClient creates a new PostIntegrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostIntegrationParamsWithHTTPClient(client *http.Client) *PostIntegrationParams {
	return &PostIntegrationParams{
		HTTPClient: client,
	}
}

/* PostIntegrationParams contains all the parameters to send to the API endpoint
   for the post integration operation.

   Typically these are written to a http.Request.
*/
type PostIntegrationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIntegrationParams) WithDefaults() *PostIntegrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIntegrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post integration params
func (o *PostIntegrationParams) WithTimeout(timeout time.Duration) *PostIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post integration params
func (o *PostIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post integration params
func (o *PostIntegrationParams) WithContext(ctx context.Context) *PostIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post integration params
func (o *PostIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post integration params
func (o *PostIntegrationParams) WithHTTPClient(client *http.Client) *PostIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post integration params
func (o *PostIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
