// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRestartInstanceParams creates a new RestartInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRestartInstanceParams() *RestartInstanceParams {
	return &RestartInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRestartInstanceParamsWithTimeout creates a new RestartInstanceParams object
// with the ability to set a timeout on a request.
func NewRestartInstanceParamsWithTimeout(timeout time.Duration) *RestartInstanceParams {
	return &RestartInstanceParams{
		timeout: timeout,
	}
}

// NewRestartInstanceParamsWithContext creates a new RestartInstanceParams object
// with the ability to set a context for a request.
func NewRestartInstanceParamsWithContext(ctx context.Context) *RestartInstanceParams {
	return &RestartInstanceParams{
		Context: ctx,
	}
}

// NewRestartInstanceParamsWithHTTPClient creates a new RestartInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewRestartInstanceParamsWithHTTPClient(client *http.Client) *RestartInstanceParams {
	return &RestartInstanceParams{
		HTTPClient: client,
	}
}

/* RestartInstanceParams contains all the parameters to send to the API endpoint
   for the restart instance operation.

   Typically these are written to a http.Request.
*/
type RestartInstanceParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	/* Selector.

	   selector
	*/
	Selector *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the restart instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestartInstanceParams) WithDefaults() *RestartInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the restart instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RestartInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the restart instance params
func (o *RestartInstanceParams) WithTimeout(timeout time.Duration) *RestartInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the restart instance params
func (o *RestartInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the restart instance params
func (o *RestartInstanceParams) WithContext(ctx context.Context) *RestartInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the restart instance params
func (o *RestartInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the restart instance params
func (o *RestartInstanceParams) WithHTTPClient(client *http.Client) *RestartInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the restart instance params
func (o *RestartInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the restart instance params
func (o *RestartInstanceParams) WithID(id uint64) *RestartInstanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the restart instance params
func (o *RestartInstanceParams) SetID(id uint64) {
	o.ID = id
}

// WithSelector adds the selector to the restart instance params
func (o *RestartInstanceParams) WithSelector(selector *string) *RestartInstanceParams {
	o.SetSelector(selector)
	return o
}

// SetSelector adds the selector to the restart instance params
func (o *RestartInstanceParams) SetSelector(selector *string) {
	o.Selector = selector
}

// WriteToRequest writes these params to a swagger request
func (o *RestartInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if o.Selector != nil {

		// query param selector
		var qrSelector string

		if o.Selector != nil {
			qrSelector = *o.Selector
		}
		qSelector := qrSelector
		if qSelector != "" {

			if err := r.SetQueryParam("selector", qSelector); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
