// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewResumeInstanceParams creates a new ResumeInstanceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResumeInstanceParams() *ResumeInstanceParams {
	return &ResumeInstanceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResumeInstanceParamsWithTimeout creates a new ResumeInstanceParams object
// with the ability to set a timeout on a request.
func NewResumeInstanceParamsWithTimeout(timeout time.Duration) *ResumeInstanceParams {
	return &ResumeInstanceParams{
		timeout: timeout,
	}
}

// NewResumeInstanceParamsWithContext creates a new ResumeInstanceParams object
// with the ability to set a context for a request.
func NewResumeInstanceParamsWithContext(ctx context.Context) *ResumeInstanceParams {
	return &ResumeInstanceParams{
		Context: ctx,
	}
}

// NewResumeInstanceParamsWithHTTPClient creates a new ResumeInstanceParams object
// with the ability to set a custom HTTPClient for a request.
func NewResumeInstanceParamsWithHTTPClient(client *http.Client) *ResumeInstanceParams {
	return &ResumeInstanceParams{
		HTTPClient: client,
	}
}

/*
ResumeInstanceParams contains all the parameters to send to the API endpoint

	for the resume instance operation.

	Typically these are written to a http.Request.
*/
type ResumeInstanceParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the resume instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResumeInstanceParams) WithDefaults() *ResumeInstanceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the resume instance params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResumeInstanceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the resume instance params
func (o *ResumeInstanceParams) WithTimeout(timeout time.Duration) *ResumeInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the resume instance params
func (o *ResumeInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the resume instance params
func (o *ResumeInstanceParams) WithContext(ctx context.Context) *ResumeInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the resume instance params
func (o *ResumeInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the resume instance params
func (o *ResumeInstanceParams) WithHTTPClient(client *http.Client) *ResumeInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the resume instance params
func (o *ResumeInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the resume instance params
func (o *ResumeInstanceParams) WithID(id uint64) *ResumeInstanceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the resume instance params
func (o *ResumeInstanceParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ResumeInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
