// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// NewSaveAsDatabaseParams creates a new SaveAsDatabaseParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSaveAsDatabaseParams() *SaveAsDatabaseParams {
	return &SaveAsDatabaseParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSaveAsDatabaseParamsWithTimeout creates a new SaveAsDatabaseParams object
// with the ability to set a timeout on a request.
func NewSaveAsDatabaseParamsWithTimeout(timeout time.Duration) *SaveAsDatabaseParams {
	return &SaveAsDatabaseParams{
		timeout: timeout,
	}
}

// NewSaveAsDatabaseParamsWithContext creates a new SaveAsDatabaseParams object
// with the ability to set a context for a request.
func NewSaveAsDatabaseParamsWithContext(ctx context.Context) *SaveAsDatabaseParams {
	return &SaveAsDatabaseParams{
		Context: ctx,
	}
}

// NewSaveAsDatabaseParamsWithHTTPClient creates a new SaveAsDatabaseParams object
// with the ability to set a custom HTTPClient for a request.
func NewSaveAsDatabaseParamsWithHTTPClient(client *http.Client) *SaveAsDatabaseParams {
	return &SaveAsDatabaseParams{
		HTTPClient: client,
	}
}

/*
SaveAsDatabaseParams contains all the parameters to send to the API endpoint

	for the save as database operation.

	Typically these are written to a http.Request.
*/
type SaveAsDatabaseParams struct {

	/* Body.

	   SaveAs database request body parameter
	*/
	Body *models.SaveAsRequest

	// InstanceID.
	//
	// Format: uint64
	InstanceID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the save as database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveAsDatabaseParams) WithDefaults() *SaveAsDatabaseParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the save as database params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveAsDatabaseParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the save as database params
func (o *SaveAsDatabaseParams) WithTimeout(timeout time.Duration) *SaveAsDatabaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save as database params
func (o *SaveAsDatabaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save as database params
func (o *SaveAsDatabaseParams) WithContext(ctx context.Context) *SaveAsDatabaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save as database params
func (o *SaveAsDatabaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save as database params
func (o *SaveAsDatabaseParams) WithHTTPClient(client *http.Client) *SaveAsDatabaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save as database params
func (o *SaveAsDatabaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the save as database params
func (o *SaveAsDatabaseParams) WithBody(body *models.SaveAsRequest) *SaveAsDatabaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the save as database params
func (o *SaveAsDatabaseParams) SetBody(body *models.SaveAsRequest) {
	o.Body = body
}

// WithInstanceID adds the instanceID to the save as database params
func (o *SaveAsDatabaseParams) WithInstanceID(instanceID uint64) *SaveAsDatabaseParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the save as database params
func (o *SaveAsDatabaseParams) SetInstanceID(instanceID uint64) {
	o.InstanceID = instanceID
}

// WriteToRequest writes these params to a swagger request
func (o *SaveAsDatabaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param instanceId
	if err := r.SetPathParam("instanceId", swag.FormatUint64(o.InstanceID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
