// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStackParams creates a new StackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStackParams() *StackParams {
	return &StackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStackParamsWithTimeout creates a new StackParams object
// with the ability to set a timeout on a request.
func NewStackParamsWithTimeout(timeout time.Duration) *StackParams {
	return &StackParams{
		timeout: timeout,
	}
}

// NewStackParamsWithContext creates a new StackParams object
// with the ability to set a context for a request.
func NewStackParamsWithContext(ctx context.Context) *StackParams {
	return &StackParams{
		Context: ctx,
	}
}

// NewStackParamsWithHTTPClient creates a new StackParams object
// with the ability to set a custom HTTPClient for a request.
func NewStackParamsWithHTTPClient(client *http.Client) *StackParams {
	return &StackParams{
		HTTPClient: client,
	}
}

/* StackParams contains all the parameters to send to the API endpoint
   for the stack operation.

   Typically these are written to a http.Request.
*/
type StackParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StackParams) WithDefaults() *StackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stack params
func (o *StackParams) WithTimeout(timeout time.Duration) *StackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stack params
func (o *StackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stack params
func (o *StackParams) WithContext(ctx context.Context) *StackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stack params
func (o *StackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stack params
func (o *StackParams) WithHTTPClient(client *http.Client) *StackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stack params
func (o *StackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the stack params
func (o *StackParams) WithName(name string) *StackParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the stack params
func (o *StackParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
