// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-manager/swagger/sdk/models"
)

// UpdateDatabaseByIDReader is a Reader for the UpdateDatabaseByID structure.
type UpdateDatabaseByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDatabaseByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDatabaseByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUpdateDatabaseByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateDatabaseByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewUpdateDatabaseByIDUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateDatabaseByIDOK creates a UpdateDatabaseByIDOK with default headers values
func NewUpdateDatabaseByIDOK() *UpdateDatabaseByIDOK {
	return &UpdateDatabaseByIDOK{}
}

/*
UpdateDatabaseByIDOK describes a response with status code 200, with default header values.

UpdateDatabaseByIDOK update database by Id o k
*/
type UpdateDatabaseByIDOK struct {
	Payload *models.Database
}

// IsSuccess returns true when this update database by Id o k response has a 2xx status code
func (o *UpdateDatabaseByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update database by Id o k response has a 3xx status code
func (o *UpdateDatabaseByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update database by Id o k response has a 4xx status code
func (o *UpdateDatabaseByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update database by Id o k response has a 5xx status code
func (o *UpdateDatabaseByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update database by Id o k response a status code equal to that given
func (o *UpdateDatabaseByIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update database by Id o k response
func (o *UpdateDatabaseByIDOK) Code() int {
	return 200
}

func (o *UpdateDatabaseByIDOK) Error() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdOK  %+v", 200, o.Payload)
}

func (o *UpdateDatabaseByIDOK) String() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdOK  %+v", 200, o.Payload)
}

func (o *UpdateDatabaseByIDOK) GetPayload() *models.Database {
	return o.Payload
}

func (o *UpdateDatabaseByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Database)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDatabaseByIDUnauthorized creates a UpdateDatabaseByIDUnauthorized with default headers values
func NewUpdateDatabaseByIDUnauthorized() *UpdateDatabaseByIDUnauthorized {
	return &UpdateDatabaseByIDUnauthorized{}
}

/*
UpdateDatabaseByIDUnauthorized describes a response with status code 401, with default header values.

UpdateDatabaseByIDUnauthorized update database by Id unauthorized
*/
type UpdateDatabaseByIDUnauthorized struct {
}

// IsSuccess returns true when this update database by Id unauthorized response has a 2xx status code
func (o *UpdateDatabaseByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update database by Id unauthorized response has a 3xx status code
func (o *UpdateDatabaseByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update database by Id unauthorized response has a 4xx status code
func (o *UpdateDatabaseByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update database by Id unauthorized response has a 5xx status code
func (o *UpdateDatabaseByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update database by Id unauthorized response a status code equal to that given
func (o *UpdateDatabaseByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update database by Id unauthorized response
func (o *UpdateDatabaseByIDUnauthorized) Code() int {
	return 401
}

func (o *UpdateDatabaseByIDUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdUnauthorized ", 401)
}

func (o *UpdateDatabaseByIDUnauthorized) String() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdUnauthorized ", 401)
}

func (o *UpdateDatabaseByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDatabaseByIDForbidden creates a UpdateDatabaseByIDForbidden with default headers values
func NewUpdateDatabaseByIDForbidden() *UpdateDatabaseByIDForbidden {
	return &UpdateDatabaseByIDForbidden{}
}

/*
UpdateDatabaseByIDForbidden describes a response with status code 403, with default header values.

UpdateDatabaseByIDForbidden update database by Id forbidden
*/
type UpdateDatabaseByIDForbidden struct {
}

// IsSuccess returns true when this update database by Id forbidden response has a 2xx status code
func (o *UpdateDatabaseByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update database by Id forbidden response has a 3xx status code
func (o *UpdateDatabaseByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update database by Id forbidden response has a 4xx status code
func (o *UpdateDatabaseByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update database by Id forbidden response has a 5xx status code
func (o *UpdateDatabaseByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update database by Id forbidden response a status code equal to that given
func (o *UpdateDatabaseByIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update database by Id forbidden response
func (o *UpdateDatabaseByIDForbidden) Code() int {
	return 403
}

func (o *UpdateDatabaseByIDForbidden) Error() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdForbidden ", 403)
}

func (o *UpdateDatabaseByIDForbidden) String() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdForbidden ", 403)
}

func (o *UpdateDatabaseByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDatabaseByIDUnsupportedMediaType creates a UpdateDatabaseByIDUnsupportedMediaType with default headers values
func NewUpdateDatabaseByIDUnsupportedMediaType() *UpdateDatabaseByIDUnsupportedMediaType {
	return &UpdateDatabaseByIDUnsupportedMediaType{}
}

/*
UpdateDatabaseByIDUnsupportedMediaType describes a response with status code 415, with default header values.

UpdateDatabaseByIDUnsupportedMediaType update database by Id unsupported media type
*/
type UpdateDatabaseByIDUnsupportedMediaType struct {
}

// IsSuccess returns true when this update database by Id unsupported media type response has a 2xx status code
func (o *UpdateDatabaseByIDUnsupportedMediaType) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update database by Id unsupported media type response has a 3xx status code
func (o *UpdateDatabaseByIDUnsupportedMediaType) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update database by Id unsupported media type response has a 4xx status code
func (o *UpdateDatabaseByIDUnsupportedMediaType) IsClientError() bool {
	return true
}

// IsServerError returns true when this update database by Id unsupported media type response has a 5xx status code
func (o *UpdateDatabaseByIDUnsupportedMediaType) IsServerError() bool {
	return false
}

// IsCode returns true when this update database by Id unsupported media type response a status code equal to that given
func (o *UpdateDatabaseByIDUnsupportedMediaType) IsCode(code int) bool {
	return code == 415
}

// Code gets the status code for the update database by Id unsupported media type response
func (o *UpdateDatabaseByIDUnsupportedMediaType) Code() int {
	return 415
}

func (o *UpdateDatabaseByIDUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdUnsupportedMediaType ", 415)
}

func (o *UpdateDatabaseByIDUnsupportedMediaType) String() string {
	return fmt.Sprintf("[PUT /databases/{id}][%d] updateDatabaseByIdUnsupportedMediaType ", 415)
}

func (o *UpdateDatabaseByIDUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
