DATABASE_MANAGER_URL: ENC[AES256_GCM,data:OH3USjwJXIyJJCVZQF6xiIK6kjLGOI/1pM//v3ZiBJHRIC0=,iv:JdhtCjnsIUy+UyxsTx6G6pi3+R/c8CB33iYN4UZ4nfw=,tag:JW04z8a1XvBbNbs3wz/6UQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:767224633206:alias/im-nonprod-secrets
          created_at: "2023-05-25T09:05:19Z"
          enc: AQICAHgKcVfytvO1DJVIcko4jrnSZygE2BN5pZdzC/9QGwx4GQGs4zNCksR3aSOqMePYVmeQAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKaxBhoZfzCJbDd2bAgEQgDuJTiW7u6GeZjAWbLBWw8KMxaX7hwJkp75NEyO2ncnj7zP8CbdNoCcajrNB19Mzjfjr6tTf8AvYfYwLOg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-24T08:26:37Z"
    mac: ENC[AES256_GCM,data:f3O7/lxWdb8HFFOBuwHuraTG1tEF0I9SD3wSmclVenqwsj98U82Ad9kj6KXMD7ONC5DvQvtpb7MBqHFIxXD6S0ol25UWUAU0WO0lE11yR/cV6G6y+6DnQrjB29S7mtLcPpTNNIoG68aXixP1R/m0yOObb+jpIPSmhvmpGqBa2zU=,iv:pwKQDgJXpL9mPovOCXTP9XS5HtSrsXx1v2xSI56FuKI=,tag:ExcTTz1CQaVt1DYutv3kfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
