DATABASE_MANAGER_URL: ENC[AES256_GCM,data:/vPSq2zMfSGD/ory0jZRQb3Qyi8N+A/CDBGI6NC4xnkmlsTi,iv:C7bE//z+C/i0mQ5tptlgF2KSzybzBbNBGLO6u3F/X04=,tag:JDSaiL/JP4AqRL0Kikd6gg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:767224633206:alias/im-prod-secrets
          created_at: "2023-05-25T09:05:23Z"
          enc: AQICAHgT8e97X192OKPTpaXOewhDtMqGDOe1qFP0c6FMw0ekSQHjCG6pjllufjJ044YOd9B1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdvQyRfDF5iYiPcKeAgEQgDuSH+I6++ZWJMGMthvkDL46CiaqgUZTXhLYDi2xRTXVqdNcjDos1CyPdESpLYUEM8VWGBBPa2cd4B1Ivw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-24T08:27:24Z"
    mac: ENC[AES256_GCM,data:n90BZdrnvAAXxmXdTf9LGOee/A3Xgu4yLDJS5zetSfdBxgvcfopg3ijGuQO8gDcO3W89Lx0Q0Vu/i7NI+eGLCuyIS2F4CcwDB8a1NFAtjrD3n755jydjkTKYUWcXO/NwB1bjYR2pdhaftos+6/3NJp2mZ1a9Xj2f/NKQ3qh7+LY=,iv:CTL1JnDkAtYcLFKiUltb0XiXTs/KZ5a/K/ih2vyNdeM=,tag:364QBa0lrcJJLKMzN8rf5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
