DATABASE_MANAGER_URL: ENC[AES256_GCM,data:bBy2a7fbTol+o3YU9nQrw2jwktz5B83kRx8QELFbTOLN6ywy3xODQOGGpVzUx8uxpNM=,iv:pya66R+oDjTXw75XFj+ZBPiX76ybh4GwewMICIFHNWI=,tag:4hYUQpBvpW0GD+SA/LpebQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-06-21T13:50:22Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gEhUFa4oTFxHPkWTJJDR9e1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIa50YXJJ5qXY2nHmAgEQgDvXeJ2Ooy+6GJbTGqcVXFNBUX8hIIBuZdUxyQHxunnMllG7DHI3ChnmZg60tgmopfeSrPkaQvCTm7WKMw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-21T13:50:40Z"
    mac: ENC[AES256_GCM,data:X/CviawYgIKYW7eI0UpbzOr9PpVGw+Mjysc4t7Xovo/LPc0zj6K3iLDyQ3UlScFb10PYQ2OnASK8Nrk1Q9iqWZGxn3uTgsoCk9hBq8dJTUJc8sk/uVuE1Em++HdpO+8lmMCY5+qBxI7ZCgVNVtWuRGEm4dAqu5cTit7iWqvkmGY=,iv:v82dIHKKeeXsFc/zoFclm5UXDC5cpJ1BKy14ZVJVHnY=,tag:BABc+s6dMqg68KCuEnU/iQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
