apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "go-chart.fullname" . }}
  labels:
    {{- include "go-chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
# For getting resources
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - create
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - patch
# KEDA
  - apiGroups:
      - http.keda.sh
    resources:
      - HTTPScaledObject
    verbs:
      - get
      - create
      - delete
