{{- $environment := index .Values "environment" }}
{{- if $environment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-chart.fullname" . }}
  labels:
    {{- include "go-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := $environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  ACCESS_TOKEN_EXPIRATION_IN_SECONDS: {{ .Values.accessTokenExpirationInSeconds | quote }}
  REFRESH_TOKEN_EXPIRATION_IN_SECONDS: {{ .Values.refreshTokenExpirationInSeconds | quote }}
  REFRESH_TOKEN_REMEMBER_ME_EXPIRATION_IN_SECONDS: {{ .Values.refreshTokenRememberMeExpirationInSeconds | quote }}

  GROUP_NAMES: {{ .Values.groups.names }}
  GROUP_HOSTNAMES: {{ .Values.groups.hostnames }}
  CORS_ALLOWED_ORIGINS: {{ join "," .Values.corsAllowOrigins | quote }}
{{- end }}
