{{- $livenessProbe := index .Values "livenessProbe" }}
{{- $readinessProbe := index .Values "readinessProbe" }}
{{- $environment := index .Values "environment" }}
{{- $secrets := index .Values "secrets" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-chart.fullname" . }}
  labels:
    {{- include "go-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if $livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.basePath }}{{ .Values.livenessProbe }}
              port: http
          {{- end }}
          {{- if $readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .Values.basePath }}{{ .Values.readinessProbe }}
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: BASE_PATH
              value: {{ .Values.basePath | default "/" }}
          {{- if or $environment $secrets }}
          envFrom:
            {{- if $environment }}
            - configMapRef:
                name: {{ include "go-chart.fullname" . }}
            {{- end }}
            {{- if $secrets }}
            - secretRef:
                name: {{ include "go-chart.fullname" . }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
              subPath: tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
