{{- $secrets := index .Values "secrets" }}
{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-chart.fullname" . }}
  labels:
    {{- include "go-chart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := $secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
