{{- $secrets := index .Values "secrets" }}
{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-chart.fullname" . }}
  labels:
    {{- include "go-chart.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := $secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
  REFRESH_TOKEN_SECRET_KEY: {{ .Values.refreshTokenSecretKey | b64enc }}

  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | b64enc }}

  ADMIN_USER_EMAIL: {{ .Values.adminUser.email | b64enc }}
  ADMIN_USER_PASSWORD: {{ .Values.adminUser.password | b64enc }}

  E2E_TEST_USER_EMAIL: {{ .Values.e2eTestUser.email | b64enc }}
  E2E_TEST_USER_PASSWORD: {{ .Values.e2eTestUser.password | b64enc }}

  PRIVATE_KEY: {{ .Values.privateKey | b64enc }}
{{- end }}
