DATABASE_MANAGER_URL: ENC[AES256_GCM,data:IX1gZR+ds9sEH+4/KtVg4H7EDfKu13c1eYIE9i1/VdJ0xGiI6Bmu0JgzwEMYBr8hgUo=,iv:WRE+INcEjVbJv26yIFbLx9/izxL3pvNNidPD1/nt8WQ=,tag:hXh8FJMDmlNGZ1N1HRRCUA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-05-11T11:16:58Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gHzzs0N7+kYwEkyL3bvEnHsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjgFWlhThhSVl8GEeAgEQgDuFyEP6XJD0HgVX6LTrqn0B5AprkRLBibYlJCAiaFPFKzZ9/pRWN5QaxWLiCD58NuzepBho0Alaw9U4eQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-12T04:52:21Z"
    mac: ENC[AES256_GCM,data:oT3wb4nUTR9NqWg0qDTNkHn8qlcq9eRqc7/BxsaBg0Qo5GfSwOr29UzngUUVZSldTQrMw+8GIXyHw6QyH9gpRaVSED5j3eukOjWrJNQ0B5J5m80C7FbF55W3J66ohZZIYpNOwPAYlmFB8jX4LmKv3WvW2h+sktPkdHjdUkhfnAU=,iv:Bs2reJx3WVl18uhOZPgx2B3zkSropM27VHeoSYrnXd4=,tag:/K1nP0lC7c8CYy0ivubuTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
