DATABASE_MANAGER_URL: ENC[AES256_GCM,data:2jqeyuZPBvuxirIwMZyrjmiXl4oAeB7hPXROpOcQ2Mr6RSYompzXpbyhr7Le1jfoIJM=,iv:WRE+INcEjVbJv26yIFbLx9/izxL3pvNNidPD1/nt8WQ=,tag:EXt9cIUBwgHG7sfI3BNM2A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-north-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-05-11T11:16:58Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gEtKolbIGsLIPj4iCxWK+t0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6sqguWZGwE7wlvpLAgEQgDv8nPE8WA7sEBdShHlEcJXeksx+V31rnmqi2FwxLjQt/KEKZ7MelKDZp8zfEXGogrgUtlKB1Y2ebP0usQ==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:767224633206:key/mrk-f5d88b4c53ec4100acd9c8ae3bde0a65
          created_at: "2022-06-06T13:55:44Z"
          enc: AQICAHhXq0BmrdaY1Tzk4VwL7hDRIr4Zx4dXQZOaXDZfdG+52gGYR9Va8gtQg7GAJUUyIQ62AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMb41wdhaKFDSWLxpeAgEQgDvI1jR1lp2AOqEdBc0f8DursXAP5jKnFD/wvYqYmcTRAHNTeH0PB+aU6c+U3Shk0gekPSFhBM7BJOZVMg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-06T13:55:45Z"
    mac: ENC[AES256_GCM,data:gedP3ODWqSC9tallRWRn17pWk4+XyeHHbqWpCigg9UaMMXREeUjRHM9vOydgndU/RDtbjfPahUsUZM+9wDfgBwuASXLk/N7s5OS0fmKqo9uhgxqUMrG2dR0n32hu/STOt6RbbPOqqOXT0rFyk6PoQsPSzYM67r9TUt7Svf7awaU=,iv:XPVHpeyDnOd/3X7c/KKMmqe9T2q0EV8a0SNOUhkdtAI=,tag:pLnCXz0YcbXenS5JdroAFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
