# consumedParameters: DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_NAME, DATABASE_HOSTNAME
# hostnameVariable: DATABASE_HOSTNAME
# stackParameters: GOOGLE_AUTH_PROJECT_ID,GOOGLE_AUTH_PRIVATE_KEY_ID,GOOGLE_AUTH_PRIVATE_KEY,GOOGLE_AUTH_CLIENT_EMAIL,GOOGLE_AUTH_CLIENT_ID
releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: dhis2/core
    version: "{{ requiredEnv "CHART_VERSION" }}"
    values:
      - image:
          repository: dhis2/{{ requiredEnv "IMAGE_REPOSITORY" }}
          tag: "{{ requiredEnv "IMAGE_TAG" }}"
          pullPolicy: {{ requiredEnv "IMAGE_PULL_POLICY" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 128m
      - dhis2Home: "{{ requiredEnv "DHIS2_HOME" }}"
      - catalinaOpts: "-Dcontext.path=/{{ requiredEnv "INSTANCE_NAME" }}"
      - javaOpts: "{{ requiredEnv "JAVA_OPTS" }}"
      - minReadySeconds: {{ requiredEnv "MIN_READY_SECONDS" }}
      - startupProbe:
          failureThreshold: {{ requiredEnv "STARTUP_PROBE_FAILURE_THRESHOLD" }}
          periodSeconds: {{ requiredEnv "STARTUP_PROBE_PERIOD_SECONDS" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - livenessProbe:
          timeoutSeconds: {{ requiredEnv "LIVENESS_PROBE_TIMEOUT_SECONDS" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - readinessProbe:
          timeoutSeconds: {{ requiredEnv "READINESS_PROBE_TIMEOUT_SECONDS" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - commonLabels:
          im: "true"
          im-default: "true"
          im-deployment-id: "{{ requiredEnv "DEPLOYMENT_ID" }}"
          im-instance-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "dhis2"
          im-creation-timestamp: "{{ requiredEnv "INSTANCE_CREATION_TIMESTAMP" }}"
          im-ttl: "{{ requiredEnv "INSTANCE_TTL" }}"

      {{- if eq (requiredEnv "STORAGE_TYPE") "minio" }}
      - minIOConfig: |
          filestore.provider = s3
          filestore.container = dhis2
          filestore.endpoint = http://{{ requiredEnv "INSTANCE_NAME" }}-minio.{{ requiredEnv "INSTANCE_NAMESPACE" }}.svc:9000
          filestore.location = eu-west-1
          filestore.identity = dhisdhis
          filestore.secret = dhisdhis
      {{- end }}

      {{- if eq (requiredEnv "STORAGE_TYPE") "s3" }}
      - S3Config: |
          filestore.provider = aws-s3
          filestore.container = {{ requiredEnv "S3_BUCKET" }}
          filestore.location = {{ requiredEnv "S3_REGION" }}
          filestore.identity = {{ requiredEnv "S3_IDENTITY" }}
          filestore.secret = {{ requiredEnv "S3_SECRET" }}
      {{- end }}

      - dhisConfig: |
          connection.dialect = org.hibernate.dialect.PostgreSQLDialect
          connection.driver_class = org.postgresql.Driver
          connection.url = jdbc:postgresql://{{ requiredEnv "DATABASE_HOSTNAME" }}/{{ requiredEnv "DATABASE_NAME" }}
          connection.username = {{ requiredEnv "DATABASE_USERNAME" }}
          connection.password = {{ requiredEnv "DATABASE_PASSWORD" }}
          # Database schema behavior, can be validate, update, create, create-drop
          connection.schema = update
          # Server base URL
          server.base.url = https://{{ requiredEnv "INSTANCE_HOSTNAME" }}/{{ requiredEnv "INSTANCE_NAME" }}
          # This will ensure the secure property of the JSESSIONID cookie is set to true
          server.https = on
          flyway.migrate_out_of_order = {{ requiredEnv "FLYWAY_MIGRATE_OUT_OF_ORDER" }}
          flyway.repair_before_migration = {{ requiredEnv "FLYWAY_REPAIR_BEFORE_MIGRATION" }}
          # Enables logging of all SQL queries.
          enable.query.logging = {{ requiredEnv "ENABLE_QUERY_LOGGING" }}
          {{- if ne (requiredEnv "CUSTOM_DHIS2_CONFIG") "" }}
          {{- requiredEnv "CUSTOM_DHIS2_CONFIG" | nindent 10 }}
          {{- end }}
      - googleAuth:
          projectId: "{{ requiredEnv "GOOGLE_AUTH_PROJECT_ID" }}"
          privateKeyId: "{{ requiredEnv "GOOGLE_AUTH_PRIVATE_KEY_ID" }}"
          privateKey: '{{ requiredEnv "GOOGLE_AUTH_PRIVATE_KEY" }}'
          clientEmail: "{{ requiredEnv "GOOGLE_AUTH_CLIENT_EMAIL" }}"
          clientId: "{{ requiredEnv "GOOGLE_AUTH_CLIENT_ID" }}"
      - resources:
          requests:
            cpu: {{ requiredEnv "RESOURCES_REQUESTS_CPU" }}
            memory: {{ requiredEnv "RESOURCES_REQUESTS_MEMORY" }}

  {{- if eq (requiredEnv "STORAGE_TYPE") "minio" }}
  - name: "{{ requiredEnv "INSTANCE_NAME" }}-minio"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: bitnami/minio
    version: "{{ requiredEnv "MINIO_CHART_VERSION" }}"
    values:
      - persistence:
          size: {{ requiredEnv "MINIO_STORAGE_SIZE" }}
        annotations:
          helm.sh/resource-policy: keep
      - auth:
          rootUser: dhisdhis
          rootPassword: dhisdhis
          forcePassword: true
      - defaultBuckets: dhis2
  {{- end }}

repositories:
  - name: dhis2
    url: https://dhis2-sre.github.io/dhis2-core-helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
