# consumedParameters: DATABASE_USERNAME, DATABASE_PASSWORD, DATABASE_NAME, DATABASE_HOSTNAME
# hostnameVariable: DATABASE_HOSTNAME
# stackParameters: GOOGLE_AUTH_PROJECT_ID,GOOGLE_AUTH_PRIVATE_KEY_ID,GOOGLE_AUTH_PRIVATE_KEY,GOOGLE_AUTH_CLIENT_EMAIL,GOOGLE_AUTH_CLIENT_ID
releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: dhis2/core
    version: "{{ env "CHART_VERSION" | default "0.14.0" }}"
    values:
      - image:
          repository: dhis2/{{ env "IMAGE_REPOSITORY" | default "core" }}
          tag: "{{ env "IMAGE_TAG" | default "2.40.0" }}"
          pullPolicy: {{ env "IMAGE_PULL_POLICY" | default "IfNotPresent" }}
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 128m
      - dhis2Home: "{{ env "DHIS2_HOME" | default "/opt/dhis2" }}"
      - catalinaOpts: "-Dcontext.path=/{{ requiredEnv "INSTANCE_NAME" }}"
      - javaOpts: "{{ env "JAVA_OPTS" | default "" }}"
      - startupProbe:
          failureThreshold: {{ env "STARTUP_PROBE_FAILURE_THRESHOLD" | default 26 }}
          periodSeconds: {{ env "STARTUP_PROBE_PERIOD_SECONDS" | default 5 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - livenessProbe:
          timeoutSeconds: {{ env "LIVENESS_PROBE_TIMEOUT_SECONDS" | default 1 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - readinessProbe:
          timeoutSeconds: {{ env "READINESS_PROBE_TIMEOUT_SECONDS" | default 1 }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - commonLabels:
          im: "true"
          im-default: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "dhis2"
          im-creation-timestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ requiredEnv "INSTANCE_TTL" }}"
      - dhisConfig: |
          connection.dialect = org.hibernate.dialect.PostgreSQLDialect
          connection.driver_class = org.postgresql.Driver
          connection.url = jdbc:postgresql://{{ requiredEnv "DATABASE_HOSTNAME" }}/{{ requiredEnv "DATABASE_NAME" }}
          connection.username = {{ requiredEnv "DATABASE_USERNAME" }}
          connection.password = {{ requiredEnv "DATABASE_PASSWORD" }}
          # Database schema behavior, can be validate, update, create, create-drop
          connection.schema = update
          # Server base URL
          server.base.url = https://{{ requiredEnv "INSTANCE_HOSTNAME" }}/{{ requiredEnv "INSTANCE_NAME" }}
          flyway.migrate_out_of_order = {{ env "FLYWAY_MIGRATE_OUT_OF_ORDER" | default false }}
          flyway.repair_before_migration = {{ env "FLYWAY_REPAIR_BEFORE_MIGRATION" | default false }}
      - googleAuth:
          projectId: "{{ env "GOOGLE_AUTH_PROJECT_ID" | default "" }}"
          privateKeyId: "{{ env "GOOGLE_AUTH_PRIVATE_KEY_ID" | default "" }}"
          privateKey: {{ env "GOOGLE_AUTH_PRIVATE_KEY" | default "" }}
          clientEmail: "{{ env "GOOGLE_AUTH_CLIENT_EMAIL" | default "" }}"
          clientId: "{{ env "GOOGLE_AUTH_CLIENT_ID" | default "" }}"
      - resources:
          requests:
            cpu: {{ env "RESOURCES_REQUESTS_CPU" | default "250m" }}
            memory: {{ env "RESOURCES_REQUESTS_MEMORY" | default "1500Mi" }}

repositories:
  - name: dhis2
    url: https://dhis2-sre.github.io/dhis2-core-helm
