releases:
  - name: "{{ requiredEnv "INSTANCE_NAME" }}"
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: tons/dhis2-core
    version: "{{ env "CHART_VERSION" | default "0.4.0" }}"
    values:
      - image:
          repository: dhis2/core
          tag: "{{ env "IMAGE_TAG" | default "2.36.0-tomcat-8.5.34-jre8-alpine" }}"
      - ingress:
          enabled: true
          hostname: {{ requiredEnv "INSTANCE_HOSTNAME" }}
          path: /{{ requiredEnv "INSTANCE_NAME" }}
          certIssuer: cert-issuer-prod
      - catalinaOpts: "-Dcontext.path=/{{ requiredEnv "INSTANCE_NAME" }}"
      - livenessProbe:
          initialDelaySeconds: 180
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - readinessProbe:
          initialDelaySeconds: 180
          path: /{{ requiredEnv "INSTANCE_NAME" }}
      - podLabels:
          im: "true"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "" }}"
      - dhisConfig: |
          connection.dialect = org.hibernate.dialect.PostgreSQLDialect
          connection.driver_class = org.postgresql.Driver
          connection.url = jdbc:postgresql://{{ env "DATABASE_HOSTNAME" }}/{{ env "DATABASE_DATABASE" | default "dhis2" }}
          connection.username = {{ env "DATABASE_USERNAME" | default "dhis" }}
          connection.password = {{ env "DATABASE_PASSWORD" | default "dhis" }}
          # Database schema behavior, can be validate, update, create, create-drop
          connection.schema = update
          # Server base URL
          server.base.url = https://{{ requiredEnv "INSTANCE_HOSTNAME" }}/{{ requiredEnv "INSTANCE_NAME" }}

repositories:
  - name: tons
    url: https://helm-charts.fitfit.dk
