releases:
  - name: {{ requiredEnv "INSTANCE_NAME" }}-job
    namespace: "{{ requiredEnv "INSTANCE_NAMESPACE" }}"
    chart: tons/im-job-runner
    version: "{{ env "CHART_VERSION" | default "0.1.0" }}"
    values:
      - image:
          pullPolicy: Always
      - podLabels:
          im: "true"
          im-default: "true"
          im-deployment-id: "{{ requiredEnv "DEPLOYMENT_ID" }}"
          im-instance-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-id: "{{ requiredEnv "INSTANCE_ID" }}"
          im-type: "job"
          im-creation-timestamp: "{{ env "INSTANCE_CREATION_TIMESTAMP" | default "" }}"
          im-ttl: "{{ env "INSTANCE_TTL" | default "" }}"
      - command: "{{ requiredEnv "COMMAND" }}"
      - payload: "{{ env "PAYLOAD" | default "-" }}"
      - dhis2:
          database:
            hostname: "{{ env "DHIS2_DATABASE_HOSTNAME" | default "-" }}"
            port: "{{ env "DHIS2_DATABASE_PORT" | default "5432" }}"
            username: "{{ env "DHIS2_DATABASE_USERNAME" | default "dhis" }}"
            password: "{{ env "DHIS2_DATABASE_PASSWORD" | default "dhis" }}"
            database: "{{ env "DHIS2_DATABASE_DATABASE" | default "dhis2" }}"
          hostname: "{{ env "DHIS2_HOSTNAME" | default "-" }}"
      - imToken: "{{ env "IM_ACCESS_TOKEN" | default "-" }}"

repositories:
  - name: tons
    url: https://helm-charts.fitfit.dk
