// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CopyDatabaseRequest copy database request
//
// swagger:model CopyDatabaseRequest
type CopyDatabaseRequest struct {

	// group
	Group string `json:"group,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this copy database request
func (m *CopyDatabaseRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this copy database request based on context it is used
func (m *CopyDatabaseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CopyDatabaseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CopyDatabaseRequest) UnmarshalBinary(b []byte) error {
	var res CopyDatabaseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
