// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstanceOptionalParameter instance optional parameter
//
// swagger:model InstanceOptionalParameter
type InstanceOptionalParameter struct {

	// TODO: Rename StackOptionalParameterID to Name
	StackOptionalParameterID string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this instance optional parameter
func (m *InstanceOptionalParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instance optional parameter based on context it is used
func (m *InstanceOptionalParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstanceOptionalParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstanceOptionalParameter) UnmarshalBinary(b []byte) error {
	var res InstanceOptionalParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
