// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StackOptionalParameter stack optional parameter
//
// swagger:model StackOptionalParameter
type StackOptionalParameter struct {

	// consumed
	Consumed bool `json:"Consumed,omitempty"`

	// default value
	DefaultValue string `json:"DefaultValue,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// stack name
	StackName string `json:"StackName,omitempty"`
}

// Validate validates this stack optional parameter
func (m *StackOptionalParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this stack optional parameter based on context it is used
func (m *StackOptionalParameter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StackOptionalParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StackOptionalParameter) UnmarshalBinary(b []byte) error {
	var res StackOptionalParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
