name: e2e tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: sudo apt install httpie

      - name: Pin kubectl to version v1.23.6 (https://github.com/aws/aws-cli/issues/6920)
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          mkdir $PWD/.kube
          echo "${{ secrets.KUBECONFIG }}" > $PWD/.kube/config
          echo "KUBECONFIG=$PWD/.kube/config" >> $GITHUB_ENV

      - name: Run e2e
        run: cd scripts/instances && ./stack_tests.sh
        env:
          HTTP: http --check-status
          IM_HOST: https://dev.api.im.dhis2.org
          USER_EMAIL: ${{ secrets.CI_TEST_USER_USER_EMAIL }}
          PASSWORD: ${{ secrets.CI_TEST_USER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  send-slack-message:
    runs-on: ubuntu-latest
    if: always() && contains(needs.*.result, 'failure') && github.ref == 'refs/heads/master'
    needs: [ e2e ]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'team-backend'
          SLACK_MESSAGE: "Latest test run on master failed and needs investigation :detective-duck:. \n Commit message: ${{ github.event.head_commit.message }}"
          SLACK_COLOR: '#ff0000'