name: e2e tests

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: sudo apt install httpie

      - name: Pin kubectl to version v1.23.6 (https://github.com/aws/aws-cli/issues/6920)
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubectl
        run: |
          mkdir $PWD/.kube
          echo "${{ secrets.KUBECONFIG }}" > $PWD/.kube/config
          echo "KUBECONFIG=$PWD/.kube/config" >> $GITHUB_ENV

      - name: Run e2e
        run: cd scripts/ && ./stack_tests.sh
        env:
          HTTP: http --check-status
          IM_HOST: https://api.im.dev.test.c.dhis2.org
          USER_EMAIL: ${{ secrets.CI_TEST_USER_USER_EMAIL }}
          PASSWORD: ${{ secrets.CI_TEST_USER_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
