name: Tests, build and deploy

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

  pull_request:
    types: [opened, reopened, synchronize, labeled]

  workflow_dispatch:

# Cancel previous runs of the same workflow and PR number or branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    # TODO update the branch reference before merging the PR
    uses: dhis2-sre/gha-workflows/.github/workflows/im-test-build-deploy.yaml@DEVOPS-262
#    if: ${{ (github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')) || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    with:
      PROCESS_NAME: im-manager
      POD_NAME: im-manager
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
